import asyncio as aio
from automation.bot import Bot
from datetime import datetime as dt

def logger(msg):
    dt_now = dt.now().strftime('%H:%M:%S')
    print(f'[{dt_now}] {msg}')

class World:
    def __init__(self, bot, xy):
        # initialize bot
        self.bot = bot
        self.xy = xy

    async def farm_seclusion_zone(self):
        logger('farm: Seclusion Zone')
        await self.bot.switch_map(864/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(1098/2400, 241/1080, open_map=False) # Breeding Ground
        await self.bot.move('e', 2000)
        await self.bot.move('ne', 1000)
        await self.bot.move('e', 5000)
        await self.bot.move('se', 3000)
        await self.bot.move('e', 2000)
        await self.bot.move('se', 5000)
        await self.bot.move('s', 1200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.move('e', 500)
        await self.bot.move('se', 1200)
        await self.bot.move('s', 2000)
        await self.bot.move('se', 1500)
        await self.bot.move('s', 2000)
        await self.bot.attack()
        await self.bot.sleep(0.5)
        await self.bot.movepi(1.55, 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.use_teleporter(920/2400, 632/1080) # Pharmaceutical Room
        await self.bot.move('n', 700)
        await self.bot.move('ne', 1500)
        await self.bot.move('e', 1500)
        await self.bot.move('se', 3500)
        await self.bot.move('ne', 500)
        await self.bot.move('se', 1500)
        await self.bot.move('e', 500)
        await self.bot.move('s', 1000)
        await self.bot.move('sw', 2500)
        await self.bot.move('e', 600)
        await self.bot.move('se', 3800)
        await self.bot.move('s', 2500)
        await self.bot.move('se', 2500)
        await self.bot.move('s', 6000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3, part 2 ###')
        await self.bot.move('s', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_supply_zone(self):
        logger('farm: Supply Zone')
        await self.bot.switch_map(750/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(720/2400, 375/1080, open_map=False) # Spare Parts Warehouse
        await self.bot.move('n', 6500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.use_teleporter(827/2400, 481/1080) # Bud of Preservation
        await self.bot.move('s', 500)
        await self.bot.move('sw', 1500)
        await self.bot.move('s', 1500)
        await aio.sleep(1.5)
        await self.bot.interact()
        await self.bot.wait_for_onmap(min_duration=2)
        await self.bot.move('n', 500)
        await self.bot.move('e', 5250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.use_teleporter(893/2400, 482/1080) # Bud of Preservation
        await self.bot.move('s', 500)
        await self.bot.move('sw', 1500)
        await self.bot.move('s', 1500)
        await aio.sleep(1.5)
        await self.bot.interact()
        await self.bot.wait_for_onmap(min_duration=2)
        await self.bot.move('n', 500)
        await self.bot.move('w', 5700)
        await self.bot.move('n', 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.use_teleporter(510/2400, 594/1080) # Electrical Room
        await self.bot.move('n', 4500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.use_teleporter(512/2400, 594/1080, confirm=True) # Electrical Room
        await self.bot.move('n', 8000)
        await self.bot.move('w', 3700)
        await self.bot.move('n', 2300)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_storage_zone(self):
        logger('farm: Storage Zone')
        await self.bot.switch_map(630/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(611/2400, 534/1080, open_map=False) # Bud of Destruction
        await self.bot.move('s', 5200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###') # roamer
        await self.bot.use_teleporter(708/2400, 507/1080) # Bud of Destruction
        await self.bot.move('s', 6000)
        await self.bot.move('w', 3000)
        await self.bot.move('n', 6300)
        await self.bot.move('w', 2400)
        await self.bot.move('s', 3800)
        await self.bot.movepi(1.25, 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.use_teleporter(774/2400, 567/1080) # Outside of Control Center
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.move('n', 2500)
        await self.bot.move('nw', 1300)
        await self.bot.move('n', 700)
        await self.bot.move('w', 1000)
        await self.bot.move('nw', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.use_teleporter(773/2400, 570/1080)
        await self.bot.move('n', 2500)
        await self.bot.move('nw', 1300)
        await self.bot.move('n', 700)
        await self.bot.move('w', 1000)
        await self.bot.move('nw', 700)
        await self.bot.move('n', 2500)
        await self.bot.move('nw', 2600)
        await self.bot.move('w', 1500)
        await self.bot.move('nw', 1500)
        await self.bot.move('w', 3500)
        await self.bot.move('sw', 500)
        await self.bot.move('s', 1500)
        await self.bot.move('w', 2100)
        await self.bot.move('n', 200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###') ###
        await self.bot.use_teleporter(972/2400, 534/1080, confirm=True) # Courtyard
        await self.bot.movepi(1.4, 1000)
        await self.bot.movepi(1.7, 1600)
        await self.bot.movepi(1.8, 700)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.use_teleporter(914/2400, 532/1080, confirm=True) # Courtyard
        await self.bot.move('sw', 1800)
        await self.bot.move('nw', 700)
        await self.bot.move('w', 1000)
        await self.bot.move('nw', 500)
        await self.bot.move('w', 2000)
        await self.bot.move('sw', 500)
        await self.bot.move('w', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_base_zone(self):
        logger('farm: Base Zone')
        await self.bot.switch_map(513/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(1045/2400, 303/1080, open_map=False, move_y=0.2)
        await self.bot.move('s', 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()