import asyncio as aio
import sys
from automation.bot import Bot
from datetime import datetime as dt

def logger(msg):
    dt_now = dt.now().strftime('%H:%M:%S')
    print(f'[{dt_now}] {msg}')

class World:
    def __init__(self, bot, xy):
        # initialize bot
        self.bot = bot
        self.xy = xy

    async def farm_robot_settlement(self):
        await self.bot.switch_map(925/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(int(self.xy.width*461/2400), int(self.xy.height*747/1080))
        await self.bot.movepi(1.75, 1700)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*768/2400), int(self.xy.height*531/1080))
        await self.bot.movepi(1.75, 1900)
        await self.bot.movepi(1.95, 3500)
        await self.bot.movepi(1.75, 1200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        await self.bot.movepi(0.0, 800)
        await self.bot.attack()
        await self.bot.sleep(1)
        logger('### group 3 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*768/2400), int(self.xy.height*752/1080))
        await self.bot.movepi(1.75, 1900)
        await self.bot.movepi(1.95, 1400)
        await self.bot.movepi(1.4, 4000)
        await self.bot.movepi(1.5, 2000)
        await self.bot.movepi(1.37, 5000)
        await self.bot.movepi(1.5, 1300)
        await self.bot.movepi(1.3, 1600)
        await self.bot.movepi(1.5, 800)
        await self.bot.movepi(1.25, 300)
        await self.bot.attack()
        await self.bot.sleep(0.5)
        await self.bot.movepi(1.6, 2300)
        await self.bot.movepi(1.4, 1000)
        await self.bot.movepi(1.25, 2100)
        await self.bot.attack()
        await self.bot.sleep(2.0)
        await self.bot.movepi(1.25, 700)
        await self.bot.movepi(1.5, 100)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*575/2400), int(self.xy.height*591/1080))
        await self.bot.movepi(1.75, 1900)
        await self.bot.movepi(1.95, 1400)
        await self.bot.movepi(1.4, 4000)
        await self.bot.movepi(1.5, 2000)
        await self.bot.movepi(1.37, 5000)
        await self.bot.movepi(1.5, 1300)
        await self.bot.movepi(1.3, 1600)
        await self.bot.movepi(1.5, 800)
        await self.bot.movepi(1.25, 300)
        await self.bot.movepi(1.6, 2400)
        await self.bot.movepi(1.9, 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4, part 2 ###')
        await self.bot.movepi(1.75, 800)
        await self.bot.movepi(0.4, 1800)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_rivet_town(self):
        await self.bot.switch_map(810/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(int(self.xy.width*1024/2400), int(self.xy.height*154/1080))
        await self.bot.movepi(1.6, 1500)
        await self.bot.movepi(1.25, 1000)
        await self.bot.movepi(1.1, 1000)
        await self.bot.movepi(1.0, 2800)
        await self.bot.movepi(0.9, 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1019/2400), int(self.xy.height*544/1080))
        await self.bot.movepi(1.6, 1500)
        await self.bot.movepi(1.25, 1000)
        await self.bot.movepi(1.1, 1000)
        await self.bot.movepi(1.0, 2800)
        await self.bot.movepi(0.58, 5000)
        await self.bot.movepi(0.50, 8000)
        await self.bot.movepi(1.0, 1500)
        await self.bot.movepi(0.5, 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1045/2400), int(self.xy.height*896/1080), confirm=True)
        await self.bot.movepi(0.5, 2500)
        await self.bot.movepi(0.0, 2400)
        await self.bot.movepi(0.25, 500)
        await self.bot.movepi(0.75, 700)
        await self.bot.movepi(1.0, 7800)
        await self.bot.movepi(0.5, 2400)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###') # roamer, finetune possible
        await self.bot.movepi(0.7, 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_great_mine(self):
        await self.bot.switch_map(700/1080)
        logger('### group 1 ###')
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.5)} {int(self.xy.width*0.5)} {int(self.xy.height*0.3)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*955/2400), int(self.xy.height*729/1080))
        await self.bot.movepi(1.8, 2000)
        await self.bot.movepi(0.1, 4700)
        await self.bot.movepi(0.3, 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.movepi(0.5, 3000)
        await self.bot.movepi(0.25, 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*772/2400), int(self.xy.height*744/1080))
        await self.bot.movepi(1.5, 500)
        await self.bot.movepi(1.75, 2000)
        await self.bot.movepi(1.9, 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.movepi(0.0, 1000)
        await self.bot.movepi(0.25, 1900)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*725/2400), int(self.xy.height*650/1080))
        await self.bot.movepi(1.05, 2600)
        await self.bot.attack()
        await self.bot.sleep(0.5)
        await self.bot.movepi(1.1, 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.sleep(0.5)
        await self.bot.movepi(0.9, 3000)
        await self.bot.movepi(0.8, 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.movepi(0.75, 1300)
        await self.bot.movepi(0.3, 1500)
        await self.bot.movepi(0.0, 2500)
        await self.bot.movepi(1.8, 2000)
        await self.bot.movepi(0.25, 2800)
        await self.bot.movepi(0.5, 1700)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1026/2400), int(self.xy.height*358/1080))
        await self.bot.movepi(0.8, 2000)
        await self.bot.movepi(1.1, 4900)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8, part 2 ###') # roamer, can be finetuned
        await self.bot.sleep(0.5)
        await self.bot.movepi(0.55, 2200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9 ###') # roamer
        await self.bot.sleep(0.5)
        await self.bot.movepi(0.6, 1900)
        await self.bot.movepi(0.5, 100)
        await self.bot.movepi(0.225, 1600)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_everwinter_hill(self):
        await self.bot.switch_map(270/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(int(self.xy.width*489/2400), int(self.xy.height*876/1080), confirm=True)
        await self.bot.movepi(0.48, 3300)
        await self.bot.attack()
        await self.bot.sleep(0.5)
        await self.bot.movepi(0.5, 3000)
        await self.bot.movepi(0.9, 4000)
        await self.bot.movepi(1.1, 3000)
        await self.bot.movepi(0.95, 800)
        await self.bot.attack()
        await self.bot.sleep(0.5)
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.movepi(0.95, 600)
        await self.bot.movepi(1.1, 2000)
        await self.bot.movepi(0.8, 1800)
        await self.bot.movepi(0.85, 1700)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1136/2400), int(self.xy.height*770/1080))
        await self.bot.movepi(1.1, 6000)
        await self.bot.movepi(0.75, 700)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.movepi(0.75, 1500)
        await self.bot.movepi(0.475, 2200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_corridor(self):
        # await self.bot.switch_map(866/1080)
        # logger('### group 1 ###')
        # cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.8)} {int(self.xy.width*0.5)} {int(self.xy.height*0.2)} 1500'
        # await self.bot.dev.shell(cmd)
        # await aio.sleep(3)
        # await self.bot.use_teleporter(int(self.xy.width*966/2400), int(self.xy.height*745/1080))
        # await self.bot.movepi(1.5, 5000)
        # await self.bot.movepi(1, 3500)
        # await self.bot.attack()
        # await self.bot.wait_for_onmap()``
        # logger('### group 2 ###')
        # await self.bot.movepi(1.51, 6000)
        # await self.bot.attack()
        # await self.bot.wait_for_onmap()
        # logger('### group 2 ###')
        # await self.bot.open_map()
        # await self.bot.use_teleporter(int(self.xy.width*1270/2400), int(self.xy.height*670/1080))
        # await self.bot.movepi(1.5, 5000)
        # await self.bot.movepi(1, 3500)
        # await self.bot.movepi(1.51, 6000)
        # await self.bot.movepi(1.6, 2000)
        # await self.bot.movepi(1.5, 4300)
        # await self.bot.attack()
        # await self.bot.sleep(0.5)
        # await self.bot.movepi(0, 7300)
        # await self.bot.movepi(0.5, 3500)
        # await self.bot.attack()
        # await self.bot.wait_for_onmap()
        # logger('### group 4 ###')
        # await self.bot.open_map()
        # cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.2)} {int(self.xy.width*0.5)} {int(self.xy.height*0.7)} 1500'
        # await self.bot.dev.shell(cmd)
        # await aio.sleep(3)
        # await self.bot.use_teleporter(int(self.xy.width*1131/2400), int(self.xy.height*242/1080))
        # await self.bot.movepi(0.375, 5000)
        # await self.bot.attack()
        # await self.bot.wait_for_onmap()
        # logger('### group 4, part 2 ###') # roamer
        # await self.bot.movepi(0.6, 1500)
        # await self.bot.attack()
        # await self.bot.wait_for_onmap()
        # logger('### group 5 ###')
        # await self.bot.open_map()
        # cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.2)} {int(self.xy.width*0.5)} {int(self.xy.height*0.7)} 1500'
        # await self.bot.dev.shell(cmd)
        # await aio.sleep(3)
        # await self.bot.use_teleporter(int(self.xy.width*1046/2400), int(self.xy.height*528/1080))
        # await self.bot.movepi(1, 1000)
        # await self.bot.movepi(0.75, 1550)
        # await self.bot.attack()
        # await self.bot.sleep(0.5)
        # await self.bot.movepi(0.5, 1500)
        # await self.bot.movepi(1, 3600)
        # await self.bot.movepi(0.48, 5500)
        # await self.bot.attack()
        # await self.bot.sleep(0.5)
        # await self.bot.wait_for_onmap()
        # logger('### group 6 ###') # adjustment needed
        # sys.exit()
        await self.bot.movepi(0.249, 5900)
        await self.bot.attack()
        await self.bot.wait_for_onmap(min_duration=30)
        logger('### group 7 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*582/2400), int(self.xy.height*566/1080))
        await self.bot.movepi(1.2, 1800)
        await self.bot.movepi(1, 8500)
        await self.bot.attack()
        await self.bot.wait_for_onmap(min_duration=30)
        logger('### group 8 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1250/2400), int(self.xy.height*125/1080))
        await self.bot.movepi(1.78, 7000)
        await self.bot.movepi(1.6, 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        await self.bot.movepi(0.9, 1000)
        await self.bot.attack()
        await self.bot.sleep(1)

    async def farm_backwater_pass(self):
        await self.bot.switch_map(637/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(int(self.xy.width*941/2400), int(self.xy.height*892/1080))
        await self.bot.move('s', 5500)
        await self.bot.move('w', 6000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*790/2400), int(self.xy.height*310/1080))
        await self.bot.move('s', 6000)
        await self.bot.move('se', 3000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2, part 2 ###') # stability: roamer
        await self.bot.move('s', 500)
        await self.bot.move('e', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.move('e', 7000)
        await self.bot.move('n', 3500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*980/2400), int(self.xy.height*250/1080))
        await self.bot.move('s', 6000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.move('s', 2500)
        await self.bot.move('se', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_outlying_snow_plains(self):
        await self.bot.switch_map(506/1080, open_map=False)
        logger('### group 1 ###')
        await self.bot.use_teleporter(int(self.xy.width*1608/2400), int(self.xy.height*594/1080))
        await self.bot.move('sw', 3000)
        await self.bot.move('w', 3000)
        await self.bot.move('sw', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap(min_duration=20)
        logger('### group 2 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*944/2400), int(self.xy.height*159/1080), confirm=True)
        await self.bot.move('w', 2500)
        await self.bot.move('sw', 3000)
        await self.bot.move('w', 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*948/2400), int(self.xy.height*121/1080))
        await self.bot.move('sw', 1500)
        await self.bot.move('w', 6000)
        await self.bot.move('sw', 3000)
        await self.bot.move('w', 4100)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.move('n', 3000)
        await self.bot.move('nw', 1200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
