import asyncio as aio
from automation.bot import Bot
from datetime import datetime as dt
import sys

def logger(msg):
    dt_now = dt.now().strftime('%H:%M:%S')
    print(f'[{dt_now}] {msg}')

class World:
    def __init__(self, bot, xy):
        # initialize bot
        self.bot = bot
        self.xy = xy

    async def farm_reverie_dreamscape(self):
        await self.bot.switch_map_new(925/1080, scroll_down=True)
        logger('### group 1 ###') # roamer
        await self.bot.use_teleporter_new(1238/2400, 462/1080,
            move_x = -0.25, move_y = 0.3,
            open_map=False, confirm=True)
        await self.bot.move('n', 2800)
        await self.bot.move('w', 13000)
        await self.bot.move('n', 3000)
        await self.bot.move('nw', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 1, part 2 ###') # aggro pull
        await self.bot.movepi(0.68, 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.use_teleporter_new(1197/2400, 148/1080, confirm=True)
        await self.bot.movepi(0.5, 2800)
        await self.bot.movepi(1.0, 5000)
        await self.bot.attack()
        await self.bot.sleep(0.5)
        await self.bot.movepi(1.0, 8000)
        await self.bot.movepi(0.5, 3000)
        await self.bot.movepi(0.25, 1500)
        await self.bot.movepi(0.56, 6500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.use_teleporter_new(1361/2400, 169/1080, confirm=True)
        await self.bot.move('n', 2800)
        await self.bot.move('w', 28000)
        await self.bot.move('sw', 1200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter_new(1135/2400, 258/1080,
                                          move_y=0.4, open_map=False, confirm=True)
        await self.bot.move('n', 2800)
        await self.bot.move('w', 28000)
        await self.bot.move('nw', 1000)
        await self.bot.move('n', 750)
        await self.bot.move('nw', 750)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter_new(1135/2400, 258/1080,
                                          move_y=0.4, open_map=False, confirm=True)
        await self.bot.movepi(0.5, 2800)
        await self.bot.movepi(1.0, 28000)
        await self.bot.movepi(1.1, 700)
        await self.bot.interact()
        await self.bot.movepi(1.5, 2000)
        await self.bot.movepi(1.3, 1800)
        await self.bot.action_button()
        await self.bot.movepi(1.5, 2000)
        await self.bot.movepi(0.0, 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter_new(1134/2400, 273/1080,
                                          move_y=0.4, move_spd=700, open_map=False, confirm=True)
        await self.bot.movepi(0.5, 2800)
        await self.bot.movepi(1.0, 13000)
        await self.bot.movepi(0.5, 3000)
        await self.bot.movepi(0.25, 1500)
        await self.bot.movepi(0.56, 6000)
        await self.bot.movepi(0.5, 3300)
        await self.bot.movepi(0.9, 2300)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6, part 2 ###') # roamer
        await self.bot.movepi(0.9, 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.use_teleporter_new(687/2400, 666/1080, move_x=0.2)
        await self.bot.move('w', 2500)
        await self.bot.move('n', 4800)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7, part 2 ###') # roamer
        await self.bot.attack()
        await self.bot.wait_for_onmap(min_duration=10)
        logger('### group 8 ###')
        await self.bot.use_teleporter_new(754/2400, 160/1080)
        await self.bot.movepi(1.25, 1200)
        await self.bot.movepi(1, 8200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9 ###')
        await self.bot.use_teleporter_new(990/2400, 250/1080)
        await self.bot.movepi(1.25, 1200)
        await self.bot.movepi(1, 5500)
        await self.bot.movepi(0.92, 4400)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9, part 2 ###') # roamer
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 10 ###') # roamer
        await self.bot.use_teleporter_new(1020/2400, 200/1080)
        await self.bot.movepi(1.25, 1200)
        await self.bot.movepi(1, 5500)
        await self.bot.movepi(0.75, 4000)
        await self.bot.movepi(0.5, 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 11 ###')
        await self.bot.use_teleporter_new(1100/2400, 245/1080)
        await self.bot.movepi(1.25, 1200)
        await self.bot.movepi(1, 5500)
        await self.bot.movepi(0.9, 2000)
        await self.bot.movepi(1.0, 3000)
        await self.bot.movepi(1.1, 2000)
        await self.bot.sleep(2)
        await self.bot.movepi(1.1, 500)
        await self.bot.movepi(1.0, 5500)
        await self.bot.sleep(2)
        await self.bot.movepi(1.1, 600)
        await self.bot.movepi(1.0, 6600)
        await self.bot.movepi(0.5, 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        await self.bot.movepi(1.25, 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 12 ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter_new(980/2400, 215/1080, open_map=False, move_y=0.35) # might be incorrect
        await self.bot.movepi(1.25, 1200)
        await self.bot.movepi(1, 5500)
        await self.bot.movepi(0.9, 2000)
        await self.bot.movepi(1.0, 3000)
        await self.bot.movepi(1.1, 2000)
        await self.bot.sleep(2)
        await self.bot.movepi(1.1, 500)
        await self.bot.movepi(1.0, 5500)
        await self.bot.sleep(2)
        await self.bot.movepi(1.0, 600)
        await self.bot.movepi(1.15, 2000)
        await self.bot.interact()
        await self.bot.movepi(0.4, 200)
        await self.bot.movepi(0.5, 3500)
        await self.bot.movepi(0.6, 600)
        await self.bot.action_button()
        await self.bot.movepi(1.0, 3500)
        await self.bot.movepi(1.3, 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 13 ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter_new(980/2400, 215/1080, open_map=False, move_y=0.35)
        await self.bot.move('n', 1500)
        await self.bot.move('w', 2500)
        await self.bot.move('n', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 14 ###') # roamer
        await self.bot.use_teleporter_new(1100/2400, 450/1080)
        await self.bot.move('n', 1500)
        await self.bot.move('w', 2500)
        await self.bot.move('n', 4900)
        await self.bot.move('e', 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 15 ###')
        await self.bot.use_teleporter_new(871/2400, 164/1080)
        await self.bot.move('n', 1000)
        await self.bot.move('ne', 4700)
        await self.bot.move('e', 6700)
        await self.bot.move('s', 7000)
        await self.bot.move('sw', 1200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 15, part 2 ###') # roamer
        await self.bot.movepi(1.2, 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 16 ###')
        await self.bot.use_teleporter_new(1017/2400, 162/1080, move_y=0.35)
        await self.bot.move('n', 7400)
        await self.bot.move('w', 500)
        await self.bot.sleep(2)
        await self.bot.move('w', 2500)
        await self.bot.sleep(2)
        await self.bot.move('w', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 17 ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter_new(1015/2400, 155/1080, open_map=False, move_y=0.1)
        await self.bot.move('n', 7400)
        await self.bot.move('w', 500)
        await self.bot.sleep(2)
        await self.bot.move('w', 2500)
        await self.bot.sleep(2)
        await self.bot.move('w', 500)
        await self.bot.move('nw', 700)
        await self.bot.move('n', 5000)
        await self.bot.move('w', 1000)
        await self.bot.move('s', 3800)
        await self.bot.move('e', 1000)
        await self.bot.move('n', 5300)
        await self.bot.move('e', 4100)
        await self.bot.move('se', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 18 ###') # roamer
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter_new(1015/2400, 225/1080, open_map=False, move_y=0.15)
        await self.bot.move('n', 7400)
        await self.bot.move('w', 500)
        await self.bot.sleep(2)
        await self.bot.move('w', 2500)
        await self.bot.sleep(2)
        await self.bot.move('w', 500)
        await self.bot.move('nw', 700)
        await self.bot.move('n', 5000)
        await self.bot.move('w', 1000)
        await self.bot.move('s', 3800)
        await self.bot.move('e', 1000)
        await self.bot.move('n', 5300)
        await self.bot.move('e', 2750)
        await self.bot.move('s', 1800)
        await self.bot.interact()
        await self.bot.move('n', 4300)
        await self.bot.move('w', 200)
        await self.bot.action_button()
        await self.bot.move('w', 2600)
        await self.bot.interact()
        await self.bot.move('e', 1800)
        await self.bot.action_button()
        await self.bot.move('e', 1000)
        await self.bot.move('se', 800)
        await self.bot.move('s', 4800)
        await self.bot.move('se', 700)
        await self.bot.action_button()
        await self.bot.move('s', 4000)
        await self.bot.move('e', 3200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 19 ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter_new(1015/2400, 221/1080, open_map=False, move_y=0.15)
        await self.bot.movepi(0.5, 7400)
        await self.bot.movepi(1.0, 500)
        await self.bot.sleep(2)
        await self.bot.movepi(1.0, 2500)
        await self.bot.sleep(2)
        await self.bot.movepi(1.0, 500)
        await self.bot.movepi(0.75, 700)
        await self.bot.movepi(0.5, 5000)
        await self.bot.movepi(1.0, 1000)
        await self.bot.movepi(1.5, 3800)
        await self.bot.movepi(0.0, 1000)
        await self.bot.movepi(0.5, 5300)
        await self.bot.movepi(0.0, 2750)
        await self.bot.movepi(1.5, 1800)
        await self.bot.interact()
        await self.bot.movepi(0.5, 4300)
        await self.bot.movepi(1.0, 200)
        await self.bot.action_button()
        await self.bot.movepi(1.0, 2600)
        await self.bot.interact()
        await self.bot.movepi(0.0, 1800)
        await self.bot.action_button()
        await self.bot.movepi(0.0, 1000)
        await self.bot.movepi(1.75, 800)
        await self.bot.movepi(1.5, 4800)
        await self.bot.movepi(1.75, 700)
        await self.bot.action_button()
        await self.bot.movepi(1.5, 4000)
        await self.bot.movepi(0.0, 6200)
        await self.bot.action_button()
        await self.bot.movepi(0.0, 2000)
        await self.bot.movepi(0.19, 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### return to normal map ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter_new(870/2400, 577/1080, open_map=False)

    async def farm_childs_dream(self):
        await self.bot.switch_map(891/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(int(self.xy.width*1038/2400), int(self.xy.height*294/1080))
        await self.bot.move('ne', 2000)
        await self.bot.move('e', 2000)
        await self.bot.move('n', 1000)
        await self.bot.move('ne', 1100)
        await self.bot.move('e', 250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1038/2400), int(self.xy.height*666/1080))
        await self.bot.move('s', 9300)
        await self.bot.move('w', 5500)
        await self.bot.move('sw', 750)
        await self.bot.attack()
        await self.bot.wait_for_onmap() # warning: view rotates after fight
        logger('### group 3 ###')
        await self.bot.move('nw', 6100)
        await self.bot.attack()
        await self.bot.wait_for_onmap() # warning: view rotates after fight
        logger('### group 3, part 2 ###')
        await self.bot.move('n', 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.open_map(penacony=True)
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.8)} {int(self.xy.width*0.5)} {int(self.xy.height*0.4)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*965/2400), int(self.xy.height*460/1080))
        await self.bot.move('s', 3500)
        await self.bot.move('se', 250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*963/2400), int(self.xy.height*379/1080))
        await self.bot.move('s', 14500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*964/2400), int(self.xy.height*269/1080))
        await self.bot.move('sw', 500)
        await self.bot.move('s', 2100)
        await self.bot.move('e', 1500)
        await self.bot.move('se', 1000)
        await self.bot.move('e', 1500)
        await self.bot.move('se', 1000)
        await self.bot.move('e', 500)
        await self.bot.move('se', 500)
        await self.bot.move('e', 2000)
        await self.bot.move('se', 1500)
        await self.bot.sleep(1)
        await self.bot.action_tap(int(self.xy.width*1600/2400), int(self.xy.height*650/1080))
        await self.bot.sleep(3)
        await self.bot.move('e', 3000)
        await self.bot.move('se', 750)
        await self.bot.sleep(1)
        await self.bot.action_tap(int(self.xy.width*1577/2400), int(self.xy.height*932/1080))
        await self.bot.sleep(3)
        await self.bot.move('e', 3000)
        await self.bot.move('s', 2000)
        await self.bot.move('sw', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### return from special map ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter(int(self.xy.width*965/2400), int(self.xy.height*426/1080))

    async def farm_dreams_edge(self):
        await self.bot.switch_map(0.7176, open_map=False)
        logger('### group 1 ###')
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.5)} {int(self.xy.width*0.25)} {int(self.xy.height*0.75)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*1056/2400), int(self.xy.height*176/1080))
        await self.bot.move('e', 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1142/2400), int(self.xy.height*502/1080))
        await self.bot.move('ne', 1500)
        await self.bot.move('n', 4500)
        await self.bot.move('e', 3700)
        await self.bot.move('n', 5500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1166/2400), int(self.xy.height*120/1080))
        await self.bot.move('ne', 1500)
        await self.bot.move('n', 4500)
        await self.bot.move('e', 3700)
        await self.bot.move('n', 11250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3, part 2 ###') # stability: sometimes 2 mob misses
        await self.bot.move('e', 250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.3)} {int(self.xy.height*0.8)} {int(self.xy.width*0.6)} {int(self.xy.height*0.2)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*0.46125), int(self.xy.height*0.4112))
        await self.bot.move('n', 3000)
        await self.bot.move('nw', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4, part 2 ###')
        await self.bot.move('w', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*0.43412), int(self.xy.height*0.4204))
        await self.bot.move('n', 3500)
        await self.bot.move('e', 2750)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5, part 2 ###')
        await self.bot.move('n', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*0.46083), int(self.xy.height*0.5334))
        await self.bot.move('n', 5000)
        await self.bot.move('nw', 1500)
        await self.bot.move('n', 3000)
        await self.bot.move('w', 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.3)} {int(self.xy.height*0.5)} {int(self.xy.width*0.6)} {int(self.xy.height*0.5)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*0.355), int(self.xy.height*0.4343))
        await self.bot.move('s', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*0.3684), int(self.xy.height*0.5213))
        await self.bot.move('sw', 2750)
        await self.bot.move('nw', 1500)
        await self.bot.move('w', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*0.3546), int(self.xy.height*0.3861))
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.2)} {int(self.xy.width*0.5)} {int(self.xy.height*0.5)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*0.36584), int(self.xy.height*0.2112))
        await self.bot.move('n', 5000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 10 ###')
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.1)} {int(self.xy.width*0.5)} {int(self.xy.height*0.95)} 600'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*1289/2400), int(self.xy.height*195/1080))
        await self.bot.move('ne', 3000)
        await self.bot.move('n', 8500)
        await self.bot.move('w', 6000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()