import asyncio as aio
from automation.bot import Bot
from datetime import datetime as dt

def logger(msg):
    dt_now = dt.now().strftime('%H:%M:%S')
    print(f'[{dt_now}] {msg}')


class World:
    def __init__(self, bot, xy):
        # initialize bot
        self.bot = bot
        self.xy = xy

    async def farm(self):
        logger('Farm: Penacony')
        await self.bot.switch_world('penacony')
        # farm locations
        await self.farm_dreams_edge()
        await self.farm_childs_dream()
        await self.farm_reverie_dreamscape()

    async def farm_reverie_dreamscape(self):
        await self.bot.switch_map(925/1080)
        logger('### group 1 ###')
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.5)} {int(self.xy.width*0.2)} {int(self.xy.height*0.8)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*1613/2400), int(self.xy.height*235/1080), confirm=True)
        await self.bot.move('n', 2800)
        await self.bot.move('w', 28000)
        await self.bot.move('sw', 1200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.open_map(penacony=True)
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.5)} {int(self.xy.width*0.2)} {int(self.xy.height*0.8)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*1613/2400), int(self.xy.height*235/1080))
        await self.bot.move('n', 2800)
        await self.bot.move('w', 28000)
        await self.bot.move('nw', 1000)
        await self.bot.move('n', 750)
        await self.bot.move('nw', 750)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.open_map(penacony=True)
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.5)} {int(self.xy.width*0.2)} {int(self.xy.height*0.8)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*1613/2400), int(self.xy.height*235/1080))
        await self.bot.move('n', 2800)
        await self.bot.move('w', 13000)
        await self.bot.move('n', 3000)
        await self.bot.move('nw', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap(min_duration=30) # stability: in case attack misses
        logger('### group 4 ###')
        await self.bot.move('n', 500)
        await self.bot.move('nw', 3000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4, part 2 ###') # stability: aggro pull
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*662/2400), int(self.xy.height*877/1080))
        await self.bot.move('ne', 500)
        await self.bot.move('e', 1800)
        await self.bot.sleep(1)
        await self.bot.action_tap(int(self.xy.width*1500/2400), int(self.xy.height*640/1080))
        await self.bot.wait_for_onmap(min_duration=3)
        await self.bot.move('n', 6000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6, part 2 ###') # stability: in case of other monster is missed
        await aio.sleep(1)
        await self.bot.move('nw', 200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*974/2400), int(self.xy.height*849/1080))
        await self.bot.move('ne', 500)
        await self.bot.move('e', 1800)
        await self.bot.sleep(1)
        await self.bot.action_tap(int(self.xy.width*1500/2400), int(self.xy.height*640/1080))
        await self.bot.wait_for_onmap(min_duration=3)
        await self.bot.move('n', 8500)
        await self.bot.move('ne', 1000)
        await self.bot.move('e', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8 ###')
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.5)} {int(self.xy.width*0.8)} {int(self.xy.height*0.5)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*426/2400), int(self.xy.height*882/1080))
        await self.bot.move('w', 2500)
        await self.bot.move('n', 4800)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8, par 2 ###') # stability: roamer
        await self.bot.attack()
        await self.bot.wait_for_onmap(min_duration=10)
        logger('### group 9 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1022/2400), int(self.xy.height*771/1080))
        await self.bot.move('w', 2500)
        await self.bot.move('n', 7000)
        await self.bot.move('w', 3000)
        await self.bot.move('sw', 500)
        await self.bot.move('w', 4000)
        await self.bot.move('sw', 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9, part 2 ###') # stability: roamers
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9, part 3 ###') # stability: roamers
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 10 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1402/2400), int(self.xy.height*835/1080))
        await self.bot.move('w', 2500)
        await self.bot.move('n', 7000)
        await self.bot.move('w', 3000)
        await self.bot.move('sw', 500)
        await self.bot.move('w', 7000)
        await self.bot.move('sw', 1500)
        await self.bot.move('w', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 11 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1538/2400), int(self.xy.height*895/1080))
        await self.bot.move('w', 2500)
        await self.bot.move('n', 7000)
        await self.bot.move('w', 3000)
        await self.bot.move('sw', 500)
        await self.bot.move('w', 5000)
        await self.bot.move('s', 4000)
        await self.bot.move('se', 900)
        await self.bot.move('s', 500)
        await self.bot.sleep(1)
        await self.bot.move('se', 1000)
        await self.bot.move('s', 4000)
        await self.bot.move('se', 1000)
        await self.bot.move('s', 500)
        await self.bot.sleep(3)
        await self.bot.move('s', 4000)
        await self.bot.move('se', 1000)
        await self.bot.move('s', 3000)
        await self.bot.move('sw', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 12 ###')
        await self.bot.move('ne', 500)
        await self.bot.move('e', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 12 ###')
        await self.bot.open_map(penacony=True)
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.1)} {int(self.xy.width*0.5)} {int(self.xy.height*0.8)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*993/2400), int(self.xy.height*214/1080))
        await self.bot.move('n', 1500)
        await self.bot.move('w', 2500)
        await self.bot.move('n', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 13 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1186/2400), int(self.xy.height*402/1080))
        await self.bot.move('n', 1500)
        await self.bot.move('w', 2500)
        await self.bot.move('n', 4900)
        await self.bot.move('e', 3000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 13 ###')
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.3)} {int(self.xy.width*0.5)} {int(self.xy.height*0.6)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*957/2400), int(self.xy.height*357/1080))
        await self.bot.move('n', 1000)
        await self.bot.move('ne', 4700)
        await self.bot.move('e', 6700)
        await self.bot.move('s', 7000)
        await self.bot.move('sw', 1200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 13, part 2 ###') # stability: roamer
        await self.bot.move('sw', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 14 ###')
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.15)} {int(self.xy.width*0.5)} {int(self.xy.height*0.85)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*1254/2400), int(self.xy.height*174/1080))
        await self.bot.move('n', 7400)
        await self.bot.move('w', 500)
        await self.bot.sleep(2)
        await self.bot.move('w', 2500)
        await self.bot.sleep(2)
        await self.bot.move('w', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 15 ###')
        await self.bot.open_map(penacony=True)
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.3)} {int(self.xy.width*0.5)} {int(self.xy.height*0.7)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*1068/2400), int(self.xy.height*261/1080))
        await self.bot.move('n', 7400)
        await self.bot.move('w', 500)
        await self.bot.sleep(2)
        await self.bot.move('w', 2500)
        await self.bot.sleep(2)
        await self.bot.move('w', 500)
        await self.bot.move('nw', 700)
        await self.bot.move('n', 5000)
        await self.bot.move('w', 1000)
        await self.bot.move('s', 3800)
        await self.bot.move('e', 1000)
        await self.bot.move('n', 5300)
        await self.bot.move('e', 4100)
        await self.bot.move('se', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 16 ###')
        await self.bot.open_map(penacony=True)
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.3)} {int(self.xy.width*0.5)} {int(self.xy.height*0.7)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.adb.get_screen(dev=self.bot.dev, debug=True)
        await self.bot.use_teleporter(int(self.xy.width*1066/2400), int(self.xy.height*267/1080))
        await self.bot.move('n', 7400)
        await self.bot.move('w', 500)
        await self.bot.sleep(2)
        await self.bot.move('w', 2500)
        await self.bot.sleep(2)
        await self.bot.move('w', 500)
        await self.bot.move('nw', 700)
        await self.bot.move('n', 5000)
        await self.bot.move('w', 1000)
        await self.bot.move('s', 3800)
        await self.bot.move('e', 1000)
        await self.bot.move('n', 5300)
        await self.bot.move('e', 2750)
        await self.bot.move('s', 1800)
        await self.bot.interact()
        await self.bot.move('n', 4300)
        await self.bot.move('w', 200)
        await self.bot.action_button()
        await self.bot.move('w', 2600)
        await self.bot.interact()
        await self.bot.move('e', 1800)
        await self.bot.action_button()
        await self.bot.move('e', 1000)
        await self.bot.move('se', 800)
        await self.bot.move('s', 4800)
        await self.bot.move('se', 700)
        await self.bot.action_button()
        await self.bot.move('s', 4000)
        await self.bot.move('e', 3500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 17 ###')
        await self.bot.sleep(0.5)
        await self.bot.move('se', 500)
        await self.bot.move('e', 2500)
        await self.bot.action_button()
        await self.bot.move('e', 2000)
        await self.bot.move('ne', 1000)
        await self.bot.attack()
        logger('### return to normal map ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter(int(self.xy.width*850/2400), int(self.xy.height*600/1080))

    async def farm_childs_dream(self):
        await self.bot.switch_map(891/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(int(self.xy.width*1038/2400), int(self.xy.height*294/1080))
        await self.bot.move('ne', 2000)
        await self.bot.move('e', 2000)
        await self.bot.move('n', 1000)
        await self.bot.move('ne', 1100)
        await self.bot.move('e', 250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1038/2400), int(self.xy.height*666/1080))
        await self.bot.move('s', 9300)
        await self.bot.move('w', 5500)
        await self.bot.move('sw', 750)
        await self.bot.attack()
        await self.bot.wait_for_onmap() # warning: view rotates after fight
        logger('### group 3 ###')
        await self.bot.move('nw', 6100)
        await self.bot.attack()
        await self.bot.wait_for_onmap() # warning: view rotates after fight
        logger('### group 3, part 2 ###')
        await self.bot.move('n', 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.open_map(penacony=True)
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.8)} {int(self.xy.width*0.5)} {int(self.xy.height*0.4)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*965/2400), int(self.xy.height*460/1080))
        await self.bot.move('s', 3500)
        await self.bot.move('se', 250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*963/2400), int(self.xy.height*379/1080))
        await self.bot.move('s', 14500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*964/2400), int(self.xy.height*269/1080))
        await self.bot.move('sw', 500)
        await self.bot.move('s', 2100)
        await self.bot.move('e', 1500)
        await self.bot.move('se', 1000)
        await self.bot.move('e', 1500)
        await self.bot.move('se', 1000)
        await self.bot.move('e', 500)
        await self.bot.move('se', 500)
        await self.bot.move('e', 2000)
        await self.bot.move('se', 1500)
        await self.bot.sleep(1)
        await self.bot.action_tap(int(self.xy.width*1600/2400), int(self.xy.height*650/1080))
        await self.bot.sleep(3)
        await self.bot.move('e', 3000)
        await self.bot.move('se', 750)
        await self.bot.sleep(1)
        await self.bot.action_tap(int(self.xy.width*1577/2400), int(self.xy.height*932/1080))
        await self.bot.sleep(3)
        await self.bot.move('e', 3000)
        await self.bot.move('s', 2000)
        await self.bot.move('sw', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### return from special map ###')
        await self.bot.open_map(penacony=True)
        await self.bot.use_teleporter(int(self.xy.width*965/2400), int(self.xy.height*426/1080))

    async def farm_dreams_edge(self):
        await self.bot.switch_map(0.7176, open_map=False)
        logger('### group 1 ###')
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.5)} {int(self.xy.width*0.25)} {int(self.xy.height*0.75)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*1056/2400), int(self.xy.height*176/1080))
        await self.bot.move('e', 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1142/2400), int(self.xy.height*502/1080))
        await self.bot.move('ne', 1500)
        await self.bot.move('n', 4500)
        await self.bot.move('e', 3700)
        await self.bot.move('n', 5500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1166/2400), int(self.xy.height*120/1080))
        await self.bot.move('ne', 1500)
        await self.bot.move('n', 4500)
        await self.bot.move('e', 3700)
        await self.bot.move('n', 11250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3, part 2 ###') # stability: sometimes 2 mob misses
        await self.bot.move('e', 250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.3)} {int(self.xy.height*0.8)} {int(self.xy.width*0.6)} {int(self.xy.height*0.2)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*0.46125), int(self.xy.height*0.4112))
        await self.bot.move('n', 3000)
        await self.bot.move('nw', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4, part 2 ###')
        await self.bot.move('w', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*0.43412), int(self.xy.height*0.4204))
        await self.bot.move('n', 3500)
        await self.bot.move('e', 2750)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5, part 2 ###')
        await self.bot.move('n', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*0.46083), int(self.xy.height*0.5334))
        await self.bot.move('n', 5000)
        await self.bot.move('nw', 1500)
        await self.bot.move('n', 3000)
        await self.bot.move('w', 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.3)} {int(self.xy.height*0.5)} {int(self.xy.width*0.6)} {int(self.xy.height*0.5)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*0.355), int(self.xy.height*0.4343))
        await self.bot.move('s', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*0.3684), int(self.xy.height*0.5213))
        await self.bot.move('sw', 2750)
        await self.bot.move('nw', 1500)
        await self.bot.move('w', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*0.3546), int(self.xy.height*0.3861))
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.2)} {int(self.xy.width*0.5)} {int(self.xy.height*0.5)} 1500'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*0.36584), int(self.xy.height*0.2112))
        await self.bot.move('n', 5000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 10 ###')
        await self.bot.open_map()
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.1)} {int(self.xy.width*0.5)} {int(self.xy.height*0.95)} 600'
        await self.bot.dev.shell(cmd)
        await aio.sleep(3)
        await self.bot.use_teleporter(int(self.xy.width*1289/2400), int(self.xy.height*195/1080))
        await self.bot.move('ne', 3000)
        await self.bot.move('n', 8500)
        await self.bot.move('w', 6000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()