import asyncio as aio
from automation.bot import Bot
from datetime import datetime as dt
import sys

def logger(msg):
    dt_now = dt.now().strftime('%H:%M:%S')
    print(f'[{dt_now}] {msg}')

class World:
    def __init__(self, bot, xy):
        # initialize bot
        self.bot = bot
        self.xy = xy

    async def farm_cloudford(self):
        logger('farm: Cloudford')
        await self.bot.switch_map(511/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(926/2400, 519/1080, open_map=False) # Trove of Verdure
        await self.bot.movepi(1.75, 2300)
        await self.bot.movepi(1.5, 4000)
        await self.bot.movepi(1.75, 2300)
        await self.bot.movepi(1.5, 10000)
        await self.bot.movepi(1.7, 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2, part 2 ###') # roamer
        await self.bot.movepi(0.5, 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.use_teleporter(928/2400, 681/1080) # Trove of Verdure
        await self.bot.movepi(0.4, 7000)
        await self.bot.movepi(0.08, 3000)
        await self.bot.movepi(0, 2200)
        await self.bot.movepi(1.5, 6300)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2, part 2 ###') # roamer
        await self.bot.movepi(1.5, 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.use_teleporter(924/2400, 716/1080) # Trove of Verdure
        await self.bot.movepi(0.75, 2100)
        await self.bot.movepi(1.0, 7400)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3, part 2 ###') # roamer
        await self.bot.movepi(1.25, 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.use_teleporter(926/2400, 339/1080) # Trove of Verdure
        await self.bot.movepi(0.75, 2100)
        await self.bot.movepi(1.0, 7400)
        await self.bot.movepi(1.25, 1200)
        await self.bot.movepi(1.0, 12000)
        await self.bot.movepi(1.25, 1300)
        await self.bot.movepi(1.0, 2400)
        await self.bot.movepi(1.25, 200)
        await self.bot.movepi(1.0, 2200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4, part 2 ###') # roamer
        await self.bot.movepi(0.0, 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.use_teleporter(971/2400, 670/1080) # Skiff Boarding Area
        await self.bot.movepi(0, 9500)
        await self.bot.movepi(0.5, 500)
        await self.bot.movepi(0.75, 1500)
        await self.bot.movepi(1, 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.use_teleporter(975/2400, 531/1080) # Skiff Boarding Area
        await self.bot.movepi(0, 9700)
        await self.bot.movepi(1.5, 2300)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.use_teleporter(812/2400, 388/1080) # Bud of Memories
        await self.bot.movepi(1.5, 2900)
        await self.bot.movepi(1.8, 1400)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7, part 2 ###')
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_stargazer_navalia(self):
        logger('farm: Stargazer Navalia')
        await self.bot.switch_map(629/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(1162/2400, 914/1080, open_map=False) # Stagnant Shadow
        await self.bot.move('se', 1000)
        await self.bot.move('e', 6000)
        await self.bot.move('se', 1000)
        await self.bot.move('e', 1000)
        await self.bot.move('n', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.move('ne', 1700)
        await self.bot.move('e', 4000)
        await self.bot.move('ne', 250)
        await self.bot.move('e', 5500)
        await self.bot.move('s', 3000)
        await self.bot.move('e', 3900)
        await self.bot.move('n', 1200)
        await self.bot.move('w', 350)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.move('e', 550)
        await self.bot.move('s', 1500)
        await self.bot.move('w', 4300)
        await self.bot.move('s', 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3, part 2 ###') # roamer; TODO: probably not needed
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.use_teleporter(854/2400, 262/1080) # Ship Nursery
        await self.bot.move('nw', 750)
        await self.bot.move('n', 750)
        await self.bot.move('ne', 750)
        await self.bot.move('e', 2000)
        await self.bot.move('n', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.use_teleporter(855/2400, 565/1080) # Ship Nursery
        await self.bot.move('nw', 750)
        await self.bot.move('n', 750)
        await self.bot.move('ne', 750)
        await self.bot.move('e', 2000)
        await self.bot.move('n', 2000)
        await self.bot.move('ne', 500)
        await self.bot.move('n', 3000)
        await self.bot.move('w', 7500)
        await self.bot.move('s', 3100)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5, part 2 ###')
        await self.bot.move('e', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.use_teleporter(876/2400, 310/1080) # Cavern of Corrosion
        await self.bot.move('se', 3700)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.use_teleporter(856/2400, 708/1080) # Ship Nursery
        await self.bot.move('s', 600)
        await self.bot.move('e', 11000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7, part 2 ###')
        await self.bot.move('s', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7, part 3 ###')
        await self.bot.move('s', 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8 ###')
        await self.bot.use_teleporter(1329/2400, 496/1080) # Astral Cottage
        await self.bot.movepi(0.25, 2500)
        await self.bot.movepi(0.16, 6000)
        await self.bot.movepi(0.27, 700)
        await self.bot.movepi(0.52, 400)
        await self.bot.movepi(1.05, 2200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9 ###') # roamer
        await self.bot.movepi(1.07, 5000)
        await self.bot.movepi(1.17, 3000)
        await self.bot.movepi(0.6, 3000)
        await self.bot.movepi(0.3, 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9, part 2 ###') # roamer
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 10 ###')
        await self.bot.use_teleporter(1237/2400, 354/1080, confirm=True) # Astral Cottage
        await self.bot.movepi(0.25, 2500)
        await self.bot.movepi(0.16, 6000)
        await self.bot.movepi(0.27, 700)
        await self.bot.movepi(0.52, 400)
        await self.bot.movepi(1.05, 2200)
        await self.bot.movepi(1.07, 5000)
        await self.bot.movepi(1.17, 2900)
        await self.bot.movepi(0.62, 6600)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 11 ###')
        await self.bot.movepi(1.2, 2400)
        await self.bot.movepi(0.9, 100)
        await self.bot.attack()
        await self.bot.sleep(1)
        await self.bot.movepi(0.6, 1900)
        await self.bot.movepi(0.2, 400)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_divination_commission(self):
        logger('farm: Divination Commission')
        await self.bot.switch_map(447/1080, scroll_down=True)
        logger('### group 1 ###')
        await self.bot.use_teleporter(1280/2400, 777/1080, open_map=False) # Conclave Hall
        await self.bot.move('s', 23000)
        await self.bot.move('sw', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.move('n', 1400)
        await self.bot.move('nw', 500)
        await self.bot.move('w', 3000)
        await self.bot.move('sw', 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2, part 2 ###') # roamer
        await self.bot.move('ne', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.use_teleporter(1088/2400, 857/1080, move_y=-0.2) # Conclave Hall
        await self.bot.movepi(1.5, 24000)
        await self.bot.movepi(0.0, 4000)
        await self.bot.movepi(0.25, 1600)
        await self.bot.movepi(0.0, 2500)
        await self.bot.movepi(1.5, 1000)
        await self.bot.movepi(1.25, 1000)
        await self.bot.movepi(1.5, 3500)
        await self.bot.movepi(1.75, 3000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.use_teleporter(449/2400, 547/1080) # Spatial Terminal
        await self.bot.move('s', 3500)
        await self.bot.move('se', 3700)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4, part 2 ###') # roamer
        await self.bot.move('se', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.use_teleporter(771/2400, 474/1080, debug=True) # Spatial Terminal
        await self.bot.move('s', 3500)
        await self.bot.move('se', 5700)
        await self.bot.move('sw', 3000)
        await self.bot.move('w', 750)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5, part 2 ###') # roamer
        await self.bot.move('w', 1000)
        await self.bot.move('sw', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.use_teleporter(742/2400, 370/1080)
        await self.bot.move('s', 3500)
        await self.bot.move('se', 11200)
        await self.bot.move('e', 4000)
        await self.bot.move('ne', 1500)
        await self.bot.move('e', 2000)
        await self.bot.move('se', 1700)
        await self.bot.move('e', 3000)
        await self.bot.move('ne', 3200)
        await self.bot.move('e', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.use_teleporter(1226/2400, 844/1080, move_y=-0.1) # Bud of Aether
        await self.bot.move('sw', 3000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###') # TODO: bad fight order
        await self.bot.use_teleporter(633/2400, 721/1080, confirm=True) # Fortuna Augurstead
        await self.bot.move('n', 4000)
        await self.bot.move('nw', 1000)
        await self.bot.move('w', 1500)
        await self.bot.move('nw', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7, part 2 ###') # roamer
        await self.bot.wait_for_onmap()
        await self.bot.move('e', 100)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8 ###')
        await self.bot.use_teleporter(801/2400, 721/1080, confirm=True) # Fortuna Augurstead
        await self.bot.move('n', 4000)
        await self.bot.move('nw', 1000)
        await self.bot.move('w', 1500)
        await self.bot.move('nw', 2000)
        await self.bot.move('w', 10500)
        await self.bot.move('n', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8, part 2 ###') # roamer
        await self.bot.move('w', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9 ###')
        await self.bot.use_teleporter(779/2400, 911/1080, confirm=True) # Fortuna Augurstead
        await self.bot.move('n', 4000)
        await self.bot.move('nw', 1000)
        await self.bot.move('w', 1500)
        await self.bot.move('nw', 2000)
        await self.bot.move('w', 10500)
        await self.bot.move('sw', 2500)
        await self.bot.move('s', 12000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_artisanship_commission(self):
        logger('farm: Artisanship Commission')
        await self.bot.switch_map(576/1080, scroll_down=True)
        logger('### group 1 ###')
        await self.bot.use_teleporter(1139/2400, 252/1080, open_map=False) # Passage of the Finery Foundry
        await self.bot.move('n', 5400)
        await self.bot.move('e', 6000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.use_teleporter(934/2400, 659/1080) # Passage of the Finery Foundry
        await self.bot.move('n', 9500)
        await self.bot.move('w', 1000)
        await self.bot.sleep(2)
        await self.bot.move('s', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.use_teleporter(1016/2400, 735/1080) # Passage of the Finery Foundry
        await self.bot.move('n', 10700)
        await self.bot.move('e', 3900)
        await self.bot.move('n', 5800)
        await self.bot.move('e', 1400)
        await self.bot.sleep(2)
        await self.bot.move('s', 100)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.use_teleporter(484/2400, 759/1080) # Passage to the Sapientia Academe
        await self.bot.move('n', 7000)
        await self.bot.move('ne', 500)
        await self.bot.move('e', 5200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4, part 2 ###') # TODO: attack misses
        await self.bot.move('w', 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.use_teleporter(896/2400, 614/1080) # Passage to the Sapientia Academe
        await self.bot.move('n', 7000)
        await self.bot.move('ne', 500)
        await self.bot.move('e', 6000)
        await self.bot.move('se', 750)
        await self.bot.move('s', 750)
        await self.bot.move('w', 4500)
        await self.bot.move('s', 750)
        await self.bot.movepi(1.72, 2800)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5, part 2 ###')
        await self.bot.movepi(0.3, 1300)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.use_teleporter(895/2400, 700/1080) # Passage to the Sapientia Academe
        await self.bot.move('sw', 3000)
        await self.bot.move('w', 8000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6, part 2 ###')
        await self.bot.move('s', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.use_teleporter(863/2400, 346/1080) # Passage to the Sapientia Academe
        await self.bot.move('sw', 3000)
        await self.bot.move('w', 8000)
        await self.bot.move('s', 1500)
        await self.bot.move('w', 5000)
        await self.bot.move('nw', 2800)
        await self.bot.move('w', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8 ###')
        await self.bot.move('w', 2800)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9 ###')
        await self.bot.use_teleporter(893/2400, 109/1080) # Passage to the Sapientia Academe
        await self.bot.move('sw', 3000)
        await self.bot.move('w', 8000)
        await self.bot.move('s', 1500)
        await self.bot.move('w', 5000)
        await self.bot.move('nw', 2500)
        await self.bot.move('nw', 500)
        await self.bot.move('w', 8000)
        await self.bot.move('nw', 1500)
        await self.bot.move('w', 2950)
        await self.bot.move('n', 3600)
        await self.bot.move('w', 8000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9, part 2 ###') # roamer; TODO: far away
        await self.bot.move('w', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 10 ###')
        await self.bot.move('w', 2000)
        await self.bot.move('sw', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 11 ###')
        await self.bot.use_teleporter(1266/2400, 213/1080) # Creation Furnace
        await self.bot.move('w', 1000)
        await self.bot.move('s', 900)
        await self.bot.move('e', 1800)
        await self.bot.move('n', 2500)
        await self.bot.move('e', 3200)
        await self.bot.move('s', 3000)
        await self.bot.move('se', 300)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 12, part 2 ###') # roamer; TODO: monster far away
        await self.bot.move('e', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 12, part 3 ###') # roamer; TODO: monster far away
        await self.bot.move('ne', 1500)
        await self.bot.move('e', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 13 ###')
        await self.bot.use_teleporter(975/2400, 319/1080) # Creation Furnace
        await self.bot.move('w', 1000)
        await self.bot.move('s', 900)
        await self.bot.move('e', 1800)
        await self.bot.move('n', 2500)
        await self.bot.move('e', 3200)
        await self.bot.move('s', 3000)
        await self.bot.move('se', 1000)
        await self.bot.move('ne', 4500)
        await self.bot.move('n', 5500)
        await self.bot.move('w', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 13, part 2 ###') # TODO: monster far awaz
        await self.bot.move('nw', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap(min_duration=20)

    async def farm_fyxestroll_garden(self):
        logger('farm: Fyxestroll Garden')
        await self.bot.switch_map(688/1080, scroll_down=True)
        logger('### group 1 ###')
        await self.bot.use_teleporter(771/2400, 474/1080, open_map=False) # Cavern of Corrosion
        await self.bot.move('s', 1000)
        await self.bot.move('e', 4000)
        await self.bot.move('s', 500)
        await self.bot.move('e', 2000)
        await self.bot.move('s', 500)
        await self.bot.move('e', 1500)
        await self.bot.move('n', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.use_teleporter(845/2400, 685/1080) # Cavern of Corrosion
        await self.bot.move('s', 1000)
        await self.bot.move('e', 4000)
        await self.bot.move('se', 2500)
        await self.bot.move('ne', 3000)
        await self.bot.move('e', 1400)
        await self.bot.move('n', 1100)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.move('e', 750)
        await self.bot.move('ne', 1100)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.use_teleporter(580/2400, 727/1080) # Locufox Forest Backdoor
        await self.bot.movepi(1.5, 4700)
        await self.bot.movepi(1.25, 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.movepi(0.19, 1100)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.use_teleporter(579/2400, 439/1080) # Locufox Forest Backdoor
        await self.bot.move('s', 6500)
        await self.bot.move('se', 2000)
        await self.bot.move('s', 1000)
        await self.bot.move('se', 2500)
        await self.bot.move('s', 2000)
        await self.bot.move('se', 1000)
        await self.bot.move('s', 3000)
        await self.bot.move('w', 1500)
        await self.bot.move('n', 1200)
        await self.bot.move('w', 1800)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.use_teleporter(579/2400, 203/1080) # Locufox Forest Backdoor
        await self.bot.move('s', 6500)
        await self.bot.move('se', 2000)
        await self.bot.move('s', 1000)
        await self.bot.move('se', 2500)
        await self.bot.move('s', 2000)
        await self.bot.move('se', 1000)
        await self.bot.move('s', 3000)
        await self.bot.move('e', 3000)
        await self.bot.move('s', 700)
        await self.bot.move('se', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8 ###')
        await self.bot.move('s', 4000)
        await self.bot.move('w', 3000)
        await self.bot.attack()
        await self.bot.wait_for_onmap(min_duration=30)

    async def farm_alchemy_commission(self):
        logger('farm: Alchemy Comission')
        await self.bot.switch_map(810/1080, scroll_down=True)
        logger('### group 1 ###')
        await self.bot.use_teleporter(907/2400, 875/1080, open_map=False, move_y=-0.3) # Cavern of Corrosion
        await self.bot.move('s', 5500)
        await self.bot.move('sw', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.use_teleporter(921/2400, 701/1080) # Cavern of Corrosion
        await self.bot.move('s', 5500)
        await self.bot.move('sw', 8000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.use_teleporter(753/2400, 345/1080) # Bud of Nihility
        await self.bot.move('w', 1500)
        await self.bot.move('n', 4000)
        await self.bot.move('w', 500)
        await self.bot.move('n', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###') # roamer
        await self.bot.use_teleporter(914/2400, 439/1080) # Bud of Nihility
        await self.bot.move('w', 2500)
        await self.bot.move('n', 3000)
        await self.bot.move('w', 5000)
        await self.bot.move('s', 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4, part 2 ###') # roamer
        await self.bot.move('w', 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4, part 3 ###') # roamer
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.use_teleporter(1025/2400, 220/1080, confirm=True)
        await self.bot.movepi(1.37, 14000)
        await self.bot.movepi(1.86, 5500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5, part 2 ###') # roamer
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.use_teleporter(1280/2400, 426/1080, confirm=True)
        await self.bot.move('n', 1500)
        await self.bot.move('nw', 6500)
        await self.bot.move('w', 6000)
        await self.bot.move('sw', 3000)
        await self.bot.move('w', 3000)
        await self.bot.move('sw', 1500)
        await self.bot.move('w', 500)
        await self.bot.move('sw', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap() # 2/3
        await self.bot.wait_for_onmap() # 1/3 roamer
        logger('### group 7 ###') # roamer
        await self.bot.use_teleporter(596/2400, 695/1080)
        await self.bot.movepi(0.5, 10000)
        await self.bot.movepi(0.75, 2000)
        await self.bot.movepi(1.0, 2000)
        await self.bot.attack()
        await self.bot.sleep(0.5)
        await self.bot.movepi(0.0, 400)
        await self.bot.movepi(1.5, 4000)
        await self.bot.movepi(1.0, 1300)
        await self.bot.movepi(0.5, 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap(min_duration=30)
        logger('### group 7, part 2 ###')
        await self.bot.movepi(0.5, 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8 ###')
        # await self.bot.use_teleporter(839/2400, 304/1080)
        await self.bot.movepi(0.5, 6700)
        await self.bot.movepi(0.0, 3500)
        await self.bot.movepi(1.5, 3600)
        await self.bot.movepi(0.0, 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9 ###') # TODO: improve pathing with movepi
        await self.bot.use_teleporter(1000/2400, 270/1080)
        await self.bot.move('n', 1500)
        await self.bot.move('w', 500)
        await self.bot.move('n', 1500)
        for _ in range(8):
            await self.bot.move('e', 325)
            await self.bot.move('n', 500)
        await self.bot.move('n', 750)
        for _ in range(4):
            await self.bot.move('e', 300)
            await self.bot.move('n', 500)
        await self.bot.move('e', 1500)
        await self.bot.move('n', 250)
        await self.bot.move('e', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 10 ###')
        await self.bot.use_teleporter(1000/2400, 530/1080)
        await self.bot.move('n', 1500)
        await self.bot.move('w', 500)
        await self.bot.move('n', 1500)
        for _ in range(8):
            await self.bot.move('e', 325)
            await self.bot.move('n', 500)
        await self.bot.move('n', 750)
        for _ in range(4):
            await self.bot.move('e', 300)
            await self.bot.move('n', 500)
        await self.bot.move('e', 1500)
        await self.bot.move('n', 250)
        await self.bot.move('e', 1000)
        await self.bot.move('n', 1500)
        await self.bot.move('e', 2500)
        await self.bot.move('s', 500)
        await self.bot.move('e', 1500)
        await self.bot.move('n', 750)
        await self.bot.move('e', 1500)
        await self.bot.move('s', 800)
        await self.bot.move('e', 1700)
        await self.bot.move('s', 1200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 10, part 2 ###')
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 11 ###')
        await self.bot.use_teleporter(1004/2400, 675/1080)
        await self.bot.move('n', 1500)
        await self.bot.move('w', 500)
        await self.bot.move('n', 1500)
        for _ in range(8):
            await self.bot.move('e', 325)
            await self.bot.move('n', 500)
        await self.bot.move('n', 750)
        for _ in range(4):
            await self.bot.move('e', 300)
            await self.bot.move('n', 500)
        await self.bot.move('e', 1500)
        await self.bot.move('n', 250)
        await self.bot.move('e', 1000)
        await self.bot.move('n', 1500)
        await self.bot.move('e', 2500)
        await self.bot.move('s', 500)
        await self.bot.move('e', 1500)
        await self.bot.move('n', 750)
        await self.bot.move('e', 1500)
        await self.bot.move('s', 800)
        await self.bot.move('e', 1700)
        await self.bot.move('s', 3200)
        for _ in range(4):
            await self.bot.move('w', 400)
            await self.bot.move('s', 500)
        await self.bot.move('s', 2000)
        await self.bot.move('e', 750)
        await self.bot.move('s', 4000)
        await self.bot.move('w', 1500)
        await self.bot.move('s', 500)
        await self.bot.move('w', 2250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 11, part 2 ###')
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_scalegorge_waterscape(self):
        await self.bot.switch_map(0.85, open_map=False, scroll_down=True)
        logger('### group 1 ###')
        await self.bot.use_teleporter(1641/2400, 530/1080, open_map=False)
        await self.bot.move('s', 4400)
        await self.bot.move('e', 2000)
        await self.bot.move('n', 3300)
        await self.bot.move('e', 3800)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.use_teleporter(357/2400, 612/1080)
        await self.bot.move('w', 5400)
        await self.bot.move('s', 1300)
        await self.bot.move('w', 6500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2, part 2 ###') # roamer, can be improved
        await self.bot.move('w', 1500)
        await self.bot.move('nw', 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2, part3 ###') # roamer, can be improved
        await self.bot.movepi(1.8, 1500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.use_teleporter(693/2400, 695/1080) # Bud of Destruction
        await self.bot.move('s', 10500)
        await self.bot.move('e', 333)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.use_teleporter(962/2400, 692/1080) # Bud of Destruction
        await self.bot.move('s', 7100)
        await self.bot.move('w', 9000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.use_teleporter(816/2400, 695/1080) # Bud of Destruction
        await self.bot.move('s', 1600)
        await self.bot.move('e', 3000)
        for _ in range(12):
            await self.bot.move('s', 650)
            await self.bot.move('e', 650)
        await self.bot.move('e', 6000)
        await self.bot.move('s', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###') # attack misses
        await self.bot.move('e', 1500)
        await self.bot.move('s', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.use_teleporter(1196/2400, 361/1080) # Palace Ruin Depths
        await self.bot.move('s', 3000)
        await self.bot.move('e', 6300)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 8 ###')
        await self.bot.use_teleporter(926/2400, 618/1080)
        await self.bot.move('s', 3000)
        await self.bot.move('e', 3500)
        await self.bot.move('s', 7000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 9 ###')
        await self.bot.use_teleporter(848/2400, 257/1080) # Stagnant Shadow
        await self.bot.move('w', 3000)
        await self.bot.move('n', 750)
        await self.bot.move('w', 6500)
        await self.bot.attack()
        await self.bot.sleep(1)
        await self.bot.wait_for_onmap()
        logger('### group 10 ###')
        await self.bot.movepi(1.25, 250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
