import asyncio as aio
from automation.bot import Bot
from datetime import datetime as dt

def logger(msg):
    dt_now = dt.now().strftime('%H:%M:%S')
    print(f'[{dt_now}] {msg}')


class World:
    def __init__(self, bot, xy):
        # initialize bot
        self.bot = bot
        self.xy = xy

    async def farm(self):
        logger('Farm: Herta Space Station')
        await self.bot.switch_world('herta_space_station')
        # farm locations
        await self.farm_base_zone()
        await self.farm_storage_zone()
        await self.farm_supply_zone()
        await self.farm_seclusion_zone()

    async def farm_seclusion_zone(self):
        await self.bot.switch_map(869/1080)
        logger('### group 1 ###')
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.3)} {int(self.xy.width*0.5)} {int(self.xy.height*0.6)} 1000'
        await self.bot.dev.shell(cmd)
        await aio.sleep(2)
        await self.bot.use_teleporter(int(self.xy.width*1171/2400), int(self.xy.height*456/1080))
        await self.bot.move('e', 2000)
        await self.bot.move('ne', 1000)
        await self.bot.move('e', 5000)
        await self.bot.move('se', 3000)
        await self.bot.move('e', 2000)
        await self.bot.move('se', 5000)
        await self.bot.move('s', 1200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.move('e', 500)
        await self.bot.move('se', 1200)
        await self.bot.move('s', 2000)
        await self.bot.move('se', 1500)
        await self.bot.move('s', 2000)
        await self.bot.attack() # TODO: check this here!
        await self.bot.wait_for_onmap(min_duration=30)
        logger('### group 3 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*684/2400), int(self.xy.height*712/1080))
        await self.bot.move('n', 700)
        await self.bot.move('ne', 1500)
        await self.bot.move('e', 1500)
        await self.bot.move('se', 3500)
        await self.bot.move('ne', 500)
        await self.bot.move('se', 1500)
        await self.bot.move('e', 500)
        await self.bot.move('s', 1000)
        await self.bot.move('sw', 2500)
        await self.bot.move('e', 600)
        await self.bot.move('se', 3800)
        await self.bot.move('s', 2500)
        await self.bot.move('se', 2500)
        await self.bot.move('s', 6000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3, part 2 ###')
        await self.bot.move('s', 2000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_supply_zone(self):
        await self.bot.switch_map(750/1080)
        logger('### group 1 ###')
        await self.bot.use_teleporter(int(self.xy.width*600/2400), int(self.xy.height*300/1080))
        await self.bot.move('n', 6500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*760/2400), int(self.xy.height*670/1080))
        await self.bot.move('s', 500)
        await self.bot.move('sw', 1500)
        await self.bot.move('s', 1500)
        await aio.sleep(1.5)
        await self.bot.action_tap(int(self.xy.width*1650/2400), int(self.xy.height*650/1080))
        await self.bot.wait_for_onmap(min_duration=1)
        await self.bot.move('n', 500)
        await self.bot.move('e', 5250)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*929/2400), int(self.xy.height*611/1080))
        await self.bot.move('s', 500)
        await self.bot.move('sw', 1500)
        await self.bot.move('s', 1500)
        await aio.sleep(1.5)
        await self.bot.action_tap(int(self.xy.width*1650/2400), int(self.xy.height*650/1080))
        await self.bot.wait_for_onmap(min_duration=1)
        await self.bot.move('n', 500)
        await self.bot.move('w', 5700)
        await self.bot.move('n', 4000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*495/2400), int(self.xy.height*405/1080))
        await self.bot.move('n', 4500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*663/2400), int(self.xy.height*596/1080))
        await self.bot.move('n', 8000)
        await self.bot.move('w', 3700)
        await self.bot.move('n', 2300)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_storage_zone(self):
        await self.bot.switch_map(0.5833)
        await self.bot.use_teleporter(int(self.xy.width*0.18167), int(self.xy.height*0.4546))
        logger('### group 1 ###')
        await self.bot.move('s', 5200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 2 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*955/2400), int(self.xy.height*342/1080))
        await self.bot.move('s', 6000)
        await self.bot.move('w', 3000)
        await self.bot.move('n', 6300)
        await self.bot.move('w', 2400)
        await self.bot.move('s', 3800)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 3 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*1053/2400), int(self.xy.height*502/1080))
        await self.bot.wait_for_onmap()
        logger('### group 4 ###')
        await self.bot.move('n', 2500)
        await self.bot.move('nw', 1300)
        await self.bot.move('n', 700)
        await self.bot.move('w', 1000)
        await self.bot.move('nw', 1000)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 5 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*841/2400), int(self.xy.height*443/1080))
        await self.bot.move('n', 2500)
        await self.bot.move('nw', 1300)
        await self.bot.move('n', 700)
        await self.bot.move('w', 1000)
        await self.bot.move('nw', 700)
        await self.bot.move('n', 2500)
        await self.bot.move('nw', 2600)
        await self.bot.move('w', 1500)
        await self.bot.move('nw', 1500)
        await self.bot.move('w', 3500)
        await self.bot.move('sw', 500)
        await self.bot.move('s', 1500)
        await self.bot.move('w', 2100)
        await self.bot.move('n', 200)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 6 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*980/2400), int(self.xy.height*380/1080), confirm=True)
        await self.bot.move('s', 700)
        await self.bot.move('se', 1600)
        await self.bot.move('s', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()
        logger('### group 7 ###')
        await self.bot.open_map()
        await self.bot.use_teleporter(int(self.xy.width*900/2400), int(self.xy.height*615/1080), confirm=True)
        await self.bot.move('sw', 1800)
        await self.bot.move('nw', 700)
        await self.bot.move('w', 1000)
        await self.bot.move('nw', 500)
        await self.bot.move('w', 2000)
        await self.bot.move('sw', 500)
        await self.bot.move('w', 500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()

    async def farm_base_zone(self):
        await self.bot.switch_map(0.463)
        logger('### group 1 ###')
        cmd = f'input swipe {int(self.xy.width*0.5)} {int(self.xy.height*0.3)} {int(self.xy.width*0.5)} {int(self.xy.height*0.6)} 1000'
        await self.bot.dev.shell(cmd)
        await aio.sleep(2)
        await self.bot.use_teleporter(int(self.xy.width*0.4533), int(self.xy.height*0.1815))
        await self.bot.move('s', 2500)
        await self.bot.attack()
        await self.bot.wait_for_onmap()