import asyncio as aio
from logger import logger
from automation.bot import Bot
from datetime import datetime as dt
from sys import exit


class World:
    def __init__(self, bot):
        # initialize bot
        self.bot = bot
    async def switch(self):
        await self.bot.switch_world('the_xianzhou_luofu')
        await self.Central_Starskiff_Haven.teleport(self)
        # await self.Cloudford.grab_technique_points(self)
    
    class Central_Starskiff_Haven:
        def __init__(self):
            pass
        async def teleport(self):
            logger.info('---')
            logger.info('--- Map: Central Starskiff Haven')
            logger.info('---')
            await self.bot.switch_map(393/1080, open_map=False)
            await self.bot.use_teleporter(803/2400, 133/1080, open_map=False, move_x=0, move_y=0)  # Starskiff Jetty
        # async def grab_technique_points(self): # TODO: find something
        #     logger.info('grab Technique Points')
        #     await self.bot.movepi(0.45, 8000)
        #     await self.bot.attack()
    
    async def farm_cloudford(self):
        x = self.Cloudford(bot=self.bot)
        await x.teleport()
        await x.grab_technique_points()
    class Cloudford:
        def __init__(self, bot):
            self.bot = bot
        async def teleport(self):
            logger.info('---')
            logger.info('--- Map: Cloudford')
            logger.info('---')
            await self.bot.switch_map(511/1080)
            await self.bot.use_teleporter(925/2400, 258/1080, open_map=False, move_x=0, move_y=4)  # Trove of Verdure
        async def grab_technique_points(self):
            logger.info('grab Technique Points')
            await self.bot.use_teleporter(925/2400, 258/1080, move_x=0, move_y=4)  # Trove of Verdure
            await self.bot.movepi(0.4, 8000)
            await self.bot.movepi(0.5, 3000)
            await self.bot.movepi(0.37, 2300)
            await self.bot.attack()

     # async def farm_cloudford(self):
    #     logger.info('farm: Cloudford')
    #     await self.bot.switch_map(511/1080)
    #     logger.info('### group 1 ###')
    #     await self.bot.use_teleporter(926/2400, 519/1080, open_map=False) # Trove of Verdure
    #     await self.bot.movepi(1.75, 2300)
    #     await self.bot.movepi(1.5, 4000)
    #     await self.bot.movepi(1.75, 2300)
    #     await self.bot.movepi(1.5, 10000)
    #     await self.bot.movepi(1.7, 4000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2, part 2 ###') # roamer
    #     await self.bot.movepi(0.5, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2 ###')
    #     await self.bot.use_teleporter(1130/2400, 207/1080) # Cargo Lane
    #     await self.bot.movepi(0.46, 8800)
    #     await self.bot.movepi(1.92, 6300)
    #     await self.bot.attack()
    #     await self.bot.sleep(0.5)
    #     await self.bot.movepi(0.6, 1000)
    #     await self.bot.movepi(0.5, 5000)
    #     await self.bot.movepi(0.25, 2000)
    #     await self.bot.movepi(0.0, 1500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2, part 2 ###') # roamer
    #     await self.bot.movepi(1, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 3 ###')
    #     await self.bot.use_teleporter(924/2400, 720/1080) # Trove of Verdure
    #     await self.bot.movepi(0.75, 2100)
    #     await self.bot.movepi(1.0, 7400)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 3, part 2 ###') # roamer
    #     await self.bot.movepi(1.25, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4 ###')
    #     await self.bot.use_teleporter(926/2400, 339/1080) # Trove of Verdure
    #     await self.bot.movepi(0.75, 2100)
    #     await self.bot.movepi(1.0, 7400)
    #     await self.bot.movepi(1.25, 1200)
    #     await self.bot.movepi(1.0, 2200)
    #     await self.bot.attack()
    #     await self.bot.sleep(0.5)
    #     await self.bot.movepi(1.0, 10100)
    #     await self.bot.movepi(1.25, 1300)
    #     await self.bot.movepi(1.0, 2400)
    #     await self.bot.movepi(1.25, 200)
    #     await self.bot.movepi(1.0, 2200)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4, part 2 ###') # roamer
    #     await self.bot.movepi(0.0, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap(min_duration=5)
    #     logger.info('### group 5 ###')
    #     await self.bot.use_teleporter(971/2400, 670/1080) # Skiff Boarding Area
    #     await self.bot.movepi(0, 9500)
    #     await self.bot.movepi(0.5, 500)
    #     await self.bot.movepi(0.75, 1500)
    #     await self.bot.movepi(1, 1500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 6 ###')
    #     await self.bot.use_teleporter(975/2400, 531/1080) # Skiff Boarding Area
    #     await self.bot.movepi(0, 9700)
    #     await self.bot.movepi(1.5, 2300)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 7 ###')
    #     await self.bot.use_teleporter(812/2400, 388/1080) # Bud of Memories
    #     await self.bot.movepi(1.5, 2900)
    #     await self.bot.movepi(1.8, 1400)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 7, part 2 ###')
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    
    async def farm_fyxestroll_garden(self):
        x = self.Fyxestroll_Garden(bot=self.bot)
        await x.teleport()
        await x.path_1()
        await x.path_2()
        await x.path_3()
        await x.path_4()
        await x.path_5()
        await x.path_6()
        await x.path_7()
        await x.atk()
    class Fyxestroll_Garden:
        def __init__(self, bot):
            self.bot = bot
        async def teleport(self):
            logger.info('---')
            logger.info('--- Map: Fyxestroll Garden')
            logger.info('---')
            await self.bot.switch_map(688/1080, scroll_down=True)
            await self.bot.use_teleporter(931/2400, 383/1080, open_map=False, move_x=0, move_y=0)  # Verdant Terrace Entrance
        async def path_1(self):
            logger.info('### Path 1 ###') # roamer
            await self.bot.use_teleporter(697/2400, 153/1080, move_x=0, move_y=0)  # Path of Darkness
            await self.bot.movepi(1.75, 2100)
            await self.bot.movepi(0.05, 2800)
            await self.bot.movepi(1.8, 2500)
            await self.bot.attack_technique(5)
        async def path_2(self):
            logger.info('### Path 2 ###')
            await self.bot.use_teleporter(697/2400, 153/1080, move_x=0, move_y=0)  # Path of Darkness
            await self.bot.movepi(1.75, 2100)
            await self.bot.movepi(0.05, 2800)
            await self.bot.movepi(1.8, 2500)
            await self.bot.movepi(0.224, 4100)
            await self.bot.movepi(0.61, 500)
            await self.bot.attack_technique(5)
        async def path_3(self):
            logger.info('### Path 3 ###')
            await self.bot.use_teleporter(697/2400, 153/1080, move_x=0, move_y=0)  # Path of Darkness
            await self.bot.movepi(1.8, 2000)
            await self.bot.attack() # +2 TP
            await self.bot.sleep(0.5)
            await self.bot.movepi(0.01, 2800)
            await self.bot.movepi(1.8, 2300)
            await self.bot.movepi(0.23, 6000)
            await self.bot.movepi(1.95, 700)
            await self.bot.attack_technique(5)
        async def path_4(self):
            logger.info('### Path 4 ###') # roamer
            await self.bot.use_teleporter(579/2400, 368/1080, move_x=1, move_y=2)  # Locufox Forest Backdoor
            await self.bot.movepi(1.5, 4400)
            await self.bot.movepi(1.95, 600)
            await self.bot.attack_technique(5)
            await self.bot.movepi(1.0, 200)
            await self.bot.attack_technique(10)
            await self.bot.restore_tp(n=2)
        async def path_5(self):
            logger.info('### Path 5 ###')
            await self.bot.use_teleporter(412/2400, 603/1080, move_x=0, move_y=0)  # Bud of Abundance
            await self.bot.movepi(1.49, 3900)
            await self.bot.attack_technique(2)
        async def path_6(self):
            logger.info('### Path 6 ###') # roamer
            await self.bot.use_teleporter(412/2400, 603/1080, move_x=0, move_y=0)  # Bud of Abundance
            await self.bot.movepi(0.9, 4000)
            await self.bot.movepi(1.2, 3000)
            await self.bot.attack_technique(10)
        async def path_7(self):
            logger.info('### Path 7 ###')
            await self.bot.use_teleporter(412/2400, 603/1080, move_x=0, move_y=0)  # Bud of Abundance
            await self.bot.movepi(1.47, 5000)
            await self.bot.movepi(1.2, 2000)
            await self.bot.movepi(0.9, 1500)
            await self.bot.movepi(1.12, 2300)
            await self.bot.attack()
            await self.bot.sleep(0.5)
            await self.bot.movepi(1.2, 1500)
            await self.bot.movepi(0.7, 1000)
            await self.bot.attack_technique(5)


    # async def farm_stargazer_navalia(self):
    #     logger.info('farm: Stargazer Navalia')
    #     await self.bot.switch_map(629/1080)
    #     logger.info('### group 1 ###')
    #     await self.bot.use_teleporter(1162/2400, 914/1080, open_map=False) # Stagnant Shadow
    #     await self.bot.movepi(1.75, 1000)
    #     await self.bot.movepi(0.00, 6000)
    #     await self.bot.movepi(1.75, 1000)
    #     await self.bot.movepi(0.00, 1000)
    #     await self.bot.movepi(0.5, 1500)
    #     await self.bot.attack()
    #     await self.bot.sleep(0.5)
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2 ###')
    #     await self.bot.movepi(0.25, 1700)
    #     await self.bot.movepi(0.00, 4000)
    #     await self.bot.movepi(0.25, 250)
    #     await self.bot.movepi(0.00, 5500)
    #     await self.bot.movepi(1.5, 3000)
    #     await self.bot.movepi(0.00, 4300)
    #     await self.bot.movepi(0.5, 1300)
    #     await self.bot.movepi(1.0, 500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 3 ###')
    #     await self.bot.use_teleporter(955/2400, 366/1080) # Ship Nursery - The Burgeoning
    #     await self.bot.movepi(0.95, 2000)
    #     await self.bot.movepi(0.65, 1900)
    #     await self.bot.movepi(1.0, 1800)
    #     await self.bot.movepi(1.5, 1700)
    #     await self.bot.movepi(1.25, 1100)
    #     await self.bot.movepi(1.5, 1000)
    #     await self.bot.movepi(1.25, 1100)
    #     await self.bot.movepi(1.5, 2000)
    #     await self.bot.movepi(1.4, 2000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 3, part 2 ###')
    #     await self.bot.movepi(1.25, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4 ###')
    #     await self.bot.use_teleporter(957/2400, 421/1080) # Ship Nursery - The Burgeoning
    #     await self.bot.movepi(0.95, 2000)
    #     await self.bot.movepi(0.65, 1900)
    #     await self.bot.movepi(1.0, 1800)
    #     await self.bot.movepi(1.5, 1700)
    #     await self.bot.movepi(0.8, 1000)
    #     await self.bot.movepi(0.5, 2300)
    #     await self.bot.movepi(1.0, 2500)
    #     await self.bot.movepi(1.4, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4, part 2 ###')
    #     await self.bot.movepi(1.7, 1500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 5 ###')
    #     await self.bot.use_teleporter(855/2400, 407/1080) # Ship Nursery - The Budding
    #     await self.bot.movepi(0.75, 800)
    #     await self.bot.movepi(0.5, 800)
    #     await self.bot.movepi(0.3, 500)
    #     await self.bot.movepi(0.00, 2000)
    #     await self.bot.movepi(0.5, 2000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 6 ###')
    #     await self.bot.use_teleporter(876/2400, 443/1080) # Cavern of Corrosion
    #     await self.bot.movepi(1.75, 3300)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     await self.bot.movepi(0.38, 1300)
    #     await self.bot.attack()
    #     await aio.sleep(0.5)
    #     logger.info('### group 7 ###')
    #     await self.bot.use_teleporter(856/2400, 710/1080) # Ship Nursery - The Budding
    #     await self.bot.movepi(1.5, 700)
    #     await self.bot.movepi(0.00, 2400)
    #     await self.bot.movepi(0.5, 800)
    #     await self.bot.attack()
    #     await self.bot.sleep(0.5)
    #     await self.bot.movepi(1.5, 800)
    #     await self.bot.movepi(1.9, 500)
    #     await self.bot.movepi(0.00, 8300)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 7, part 2 ###')
    #     await self.bot.movepi(1.5, 3900)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 8 ###')
    #     await self.bot.use_teleporter(1333/2400, 490/1080) # Astral Cottage
    #     await self.bot.movepi(0.25, 2500)
    #     await self.bot.movepi(0.16, 6000)
    #     await self.bot.movepi(0.27, 700)
    #     await self.bot.movepi(0.52, 400)
    #     await self.bot.movepi(1.05, 2200)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 9 ###') # roamer
    #     await self.bot.movepi(1.07, 5000)
    #     await self.bot.movepi(1.17, 3000)
    #     await self.bot.movepi(0.6, 3000)
    #     await self.bot.movepi(0.3, 2000)
    #     await self.bot.movepi(0.0, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 9, part 2 ###') # roamer
    #     await self.bot.movepi(0.1, 1300)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 10 ###')
    #     await self.bot.use_teleporter(1237/2400, 367/1080, confirm=True) # Astral Cottage
    #     await self.bot.movepi(0.25, 2500)
    #     await self.bot.movepi(0.16, 6000)
    #     await self.bot.movepi(0.27, 700)
    #     await self.bot.movepi(0.52, 400)
    #     await self.bot.movepi(1.05, 2200)
    #     await self.bot.movepi(1.07, 5000)
    #     await self.bot.movepi(1.17, 2900)
    #     await self.bot.movepi(0.62, 6600)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 11 ###')
    #     await self.bot.movepi(1.2, 2400)
    #     await self.bot.movepi(0.9, 100)
    #     await self.bot.attack()
    #     await self.bot.sleep(1)
    #     await self.bot.movepi(0.6, 2100)
    #     await self.bot.movepi(0.2, 400)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()

    # async def farm_divination_commission(self):
    #     logger.info('farm: Divination Commission')
    #     await self.bot.switch_map(447/1080, scroll_down=True)
    #     logger.info('### group 1 ###')
    #     await self.bot.use_teleporter(1280/2400, 777/1080, open_map=False) # Conclave Hall
    #     await self.bot.movepi(1.5, 23000)
    #     await self.bot.movepi(1.25, 2000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2 ###')
    #     await self.bot.movepi(0.5, 1400)
    #     await self.bot.movepi(0.75, 500)
    #     await self.bot.movepi(1.0, 3000)
    #     await self.bot.movepi(1.25, 2500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2, part 2 ###') # roamer
    #     await self.bot.movepi(0.25, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 3 ###')
    #     await self.bot.use_teleporter(1088/2400, 857/1080, move_y=-0.2) # Conclave Hall
    #     await self.bot.movepi(1.5, 24300)
    #     await self.bot.movepi(0.07, 6500)
    #     await self.bot.movepi(0.0, 1400)
    #     await self.bot.movepi(1.5, 1500)
    #     await self.bot.movepi(1.35, 1400)
    #     await self.bot.movepi(1.5, 3200)
    #     await self.bot.movepi(1.76, 2500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4 ###')
    #     await self.bot.use_teleporter(443/2400, 548/1080) # Spatial Terminal
    #     await self.bot.movepi(1.5, 3700)
    #     await self.bot.movepi(1.75, 4200)
    #     await self.bot.movepi(0.2, 900)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4, part 2 ###') # roamer
    #     await self.bot.movepi(1.6, 2000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 5 ###')
    #     await self.bot.use_teleporter(740/2400, 363/1080) # Spatial Terminal
    #     await self.bot.movepi(1.5, 3700)
    #     await self.bot.movepi(1.75, 5700)
    #     await self.bot.movepi(1.25, 3000)
    #     await self.bot.movepi(1.0, 750)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 5, part 2 ###') # roamer
    #     await self.bot.movepi(1.0, 1400)
    #     await self.bot.movepi(1.55, 1500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 6 ###')
    #     await self.bot.use_teleporter(742/2400, 376/1080)
    #     await self.bot.movepi(1.5, 3700)
    #     await self.bot.movepi(1.75, 11300)
    #     await self.bot.movepi(0.00, 4000)
    #     await self.bot.movepi(0.25, 1500)
    #     await self.bot.movepi(0.00, 2000)
    #     await self.bot.movepi(1.75, 1700)
    #     await self.bot.movepi(0.00, 3000)
    #     await self.bot.movepi(0.25, 3200)
    #     await self.bot.movepi(0.00, 1500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 7 ###')
    #     await self.bot.use_teleporter(1226/2400, 844/1080, move_y=-0.1) # Bud of Aether
    #     await self.bot.movepi(1.25, 3000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 7 ###')
    #     await self.bot.use_teleporter(628/2400, 719/1080, confirm=True) # Fortuna Augurstead
    #     await self.bot.movepi(0.5, 4000)
    #     await self.bot.movepi(0.75, 1000)
    #     await self.bot.movepi(1.0, 1500)
    #     await self.bot.movepi(0.75, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 7, part 2 ###') # roamer
    #     await self.bot.movepi(0.75, 1500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 8 ###')
    #     await self.bot.use_teleporter(804/2400, 718/1080, confirm=True) # Fortuna Augurstead
    #     await self.bot.movepi(0.5, 4000)
    #     await self.bot.movepi(0.75, 1000)
    #     await self.bot.movepi(1.0, 1500)
    #     await self.bot.movepi(0.75, 2000)
    #     await self.bot.movepi(1.0, 10500)
    #     await self.bot.movepi(0.5, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 8, part 2 ###') # roamer
    #     await self.bot.movepi(1.0, 2000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 9 ###')
    #     await self.bot.use_teleporter(779/2400, 911/1080, confirm=True) # Fortuna Augurstead
    #     await self.bot.movepi(0.5, 4000)
    #     await self.bot.movepi(0.75, 1000)
    #     await self.bot.movepi(1.0, 1500)
    #     await self.bot.movepi(0.75, 2000)
    #     await self.bot.movepi(1.0, 10500)
    #     await self.bot.movepi(1.25, 2500)
    #     await self.bot.movepi(1.5, 11000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()

    # async def farm_artisanship_commission(self):
    #     logger.info('farm: Artisanship Commission')
    #     await self.bot.switch_map(576/1080, scroll_down=True)
    #     logger.info('### group 1 ###')
    #     await self.bot.use_teleporter(1139/2400, 252/1080, open_map=False) # Passage of the Finery Foundry
    #     await self.bot.movepi(0.5, 5200)
    #     await self.bot.movepi(0.00, 6200)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2 ###')
    #     await self.bot.use_teleporter(934/2400, 659/1080) # Passage of the Finery Foundry
    #     await self.bot.movepi(0.5, 9700)
    #     await self.bot.movepi(1.0, 1000)
    #     await self.bot.sleep(2)
    #     await self.bot.movepi(1.6, 600)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 3 ###')
    #     await self.bot.use_teleporter(1016/2400, 735/1080) # Passage of the Finery Foundry
    #     await self.bot.movepi(0.5, 10900)
    #     await self.bot.movepi(0.00, 3900)
    #     await self.bot.movepi(0.5, 5900)
    #     await self.bot.movepi(0.00, 1400)
    #     await self.bot.sleep(2)
    #     await self.bot.movepi(1.5, 500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4 ###')
    #     await self.bot.use_teleporter(484/2400, 759/1080) # Passage to the Sapientia Academe
    #     await self.bot.movepi(0.5, 7000)
    #     await self.bot.movepi(0.25, 500)
    #     await self.bot.movepi(0.00, 5300)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4, part 2 ###')
    #     await self.bot.movepi(1.0, 3700)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 5 ###')
    #     await self.bot.use_teleporter(895/2400, 622/1080) # Passage to the Sapientia Academe
    #     await self.bot.movepi(0.5, 7100)
    #     await self.bot.movepi(0.25, 500)
    #     await self.bot.movepi(0.00, 6100)
    #     await self.bot.movepi(1.75, 750)
    #     await self.bot.movepi(1.5, 750)
    #     await self.bot.movepi(1.0, 4500)
    #     await self.bot.movepi(1.5, 750)
    #     await self.bot.movepi(1.72, 2800)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 5, part 2 ###')
    #     await self.bot.movepi(0.3, 1300)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 6 ###')
    #     await self.bot.use_teleporter(895/2400, 700/1080) # Passage to the Sapientia Academe
    #     await self.bot.movepi(1.25, 3000)
    #     await self.bot.movepi(1.0, 8200)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 6, part 2 ###')
    #     await self.bot.movepi(1.5, 1500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 7 ###')
    #     await self.bot.use_teleporter(863/2400, 346/1080) # Passage to the Sapientia Academe
    #     await self.bot.movepi(1.25, 3000)
    #     await self.bot.movepi(1.0, 8200)
    #     await self.bot.movepi(1.5, 1500)
    #     await self.bot.movepi(1.0, 5000)
    #     await self.bot.movepi(0.75, 2800)
    #     await self.bot.movepi(1.0, 500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 8 ###')
    #     await self.bot.movepi(1.0, 2800)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 9 ###')
    #     await self.bot.use_teleporter(893/2400, 109/1080) # Passage to the Sapientia Academe
    #     await self.bot.movepi(1.25, 3000)
    #     await self.bot.movepi(1.0, 8200)
    #     await self.bot.movepi(1.5, 1500)
    #     await self.bot.movepi(1.0, 5000)
    #     await self.bot.movepi(0.75, 2500)
    #     await self.bot.movepi(0.75, 500)
    #     await self.bot.movepi(1.0, 8200)
    #     await self.bot.movepi(0.75, 1500)
    #     await self.bot.movepi(1.0, 2950)
    #     await self.bot.movepi(0.5, 3600)
    #     await self.bot.movepi(1.0, 8000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 9, part 2 ###') # roamer
    #     await self.bot.movepi(1.0, 3000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 10 ###')
    #     await self.bot.movepi(1.18, 1800)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 11 ###')
    #     await self.bot.use_teleporter(1265/2400, 213/1080) # Creation Furnace
    #     await self.bot.movepi(1.0, 1100)
    #     await self.bot.movepi(1.5, 900)
    #     await self.bot.movepi(0.00, 1800)
    #     await self.bot.movepi(0.5, 2500)
    #     await self.bot.movepi(0.00, 3300)
    #     await self.bot.movepi(1.5, 3000)
    #     await self.bot.movepi(1.75, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 12, part 2 ###') # roamer
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap(min_duration=5)
    #     logger.info('### group 12, part 3 ###') # roamer
    #     await self.bot.movepi(0.15, 3800)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 13 ###')
    #     await self.bot.use_teleporter(966/2400, 315/1080) # Creation Furnace
    #     await self.bot.movepi(1.0, 1100)
    #     await self.bot.movepi(1.5, 900)
    #     await self.bot.movepi(0.00, 1800)
    #     await self.bot.movepi(0.5, 2500)
    #     await self.bot.movepi(0.00, 3300)
    #     await self.bot.movepi(1.5, 3000)
    #     await self.bot.movepi(1.75, 1000)
    #     await self.bot.movepi(0.25, 4500)
    #     await self.bot.movepi(0.5, 5700)
    #     await self.bot.movepi(1.05, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 13, part 2 ###')
    #     await self.bot.movepi(0.6, 1800)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()

    # async def farm_alchemy_commission(self):
    #     logger.info('farm: Alchemy Comission')
    #     await self.bot.switch_map(810/1080, scroll_down=True)
    #     logger.info('### group 1 ###')
    #     await self.bot.use_teleporter(907/2400, 875/1080, open_map=False, move_y=-0.3) # Cavern of Corrosion
    #     await self.bot.movepi(1.5, 5700)
    #     await self.bot.movepi(1.25, 2000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2 ###')
    #     await self.bot.use_teleporter(921/2400, 701/1080) # Cavern of Corrosion
    #     await self.bot.movepi(1.5, 5700)
    #     await self.bot.movepi(1.25, 8200)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 3 ###')
    #     await self.bot.use_teleporter(753/2400, 345/1080) # Bud of Nihility
    #     await self.bot.movepi(1.0, 1500)
    #     await self.bot.movepi(0.5, 4100)
    #     await self.bot.movepi(1.0, 500)
    #     await self.bot.movepi(0.5, 500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4 ###') # roamer
    #     await self.bot.use_teleporter(914/2400, 439/1080) # Bud of Nihility
    #     await self.bot.movepi(1.0, 2500)
    #     await self.bot.movepi(0.5, 3100)
    #     await self.bot.movepi(1.0, 5200)
    #     await self.bot.movepi(1.5, 2200)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4, part 2 ###') # roamer
    #     await self.bot.movepi(1.1, 1700)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4, part 3 ###') # roamer
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap(min_duration=3)
    #     logger.info('### group 5 ###')
    #     await self.bot.use_teleporter(1025/2400, 220/1080, confirm=True)
    #     await self.bot.movepi(1.37, 14300)
    #     await self.bot.movepi(1.86, 5700)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 5, part 2 ###') # roamer
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 6 ###')
    #     await self.bot.use_teleporter(1280/2400, 426/1080, confirm=True) # Healer's Market
    #     await self.bot.movepi(0.5, 1500)
    #     await self.bot.movepi(0.75, 6700)
    #     await self.bot.movepi(1.0, 6200)
    #     await self.bot.movepi(1.25, 3100)
    #     await self.bot.movepi(1.0, 3100)
    #     await self.bot.movepi(1.25, 1500)
    #     await self.bot.movepi(1.0, 500)
    #     await self.bot.movepi(1.25, 500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 6, part 2 ###')
    #     await self.bot.movepi(1.25, 700)
    #     await self.bot.movepi(1.5, 300)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 7 ###') # roamer
    #     await self.bot.use_teleporter(605/2400, 705/1080) # Elixir Research Terrace
    #     await self.bot.movepi(0.5, 10300)
    #     await self.bot.movepi(0.75, 2000)
    #     await self.bot.movepi(1.0, 2000)
    #     await self.bot.attack()
    #     await self.bot.sleep(0.5)
    #     await self.bot.movepi(0.0, 400)
    #     await self.bot.movepi(1.5, 4400)
    #     await self.bot.movepi(1.0, 1300)
    #     await self.bot.movepi(0.5, 1500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 7, part 2 ###')
    #     await self.bot.movepi(1.25, 500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 8 ###')
    #     await self.bot.use_teleporter(839/2400, 304/1080) # Elixir Research Terrace
    #     await self.bot.movepi(0.5, 6900)
    #     await self.bot.movepi(0.0, 3600)
    #     await self.bot.movepi(1.5, 3700)
    #     await self.bot.movepi(0.0, 4200)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 9 ###')
    #     await self.bot.use_teleporter(1004/2400, 268/1080) # Aureate Elixir Furnace
    #     await self.bot.movepi(0.55, 2500)
    #     await self.bot.movepi(0.4, 2000)
    #     await self.bot.movepi(0.27, 1500)
    #     await self.bot.movepi(0.1, 500)
    #     await self.bot.movepi(0.45, 2500)
    #     await self.bot.movepi(0.3, 2000)
    #     await self.bot.movepi(0.00, 2400)
    #     await self.bot.movepi(1.5, 200)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 9, part 2 ###')
    #     await self.bot.movepi(0.35, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 10 ###')
    #     await self.bot.use_teleporter(1000/2400, 532/1080) # Aureate Elixir Furnace
    #     await self.bot.attack()
    #     await self.bot.sleep(0.5)
    #     await self.bot.movepi(0.55, 2500)
    #     await self.bot.movepi(0.4, 2000)
    #     await self.bot.movepi(0.27, 1500)
    #     await self.bot.movepi(0.1, 500)
    #     await self.bot.movepi(0.45, 2500)
    #     await self.bot.movepi(0.3, 2000)
    #     await self.bot.movepi(0.00, 2500)
    #     await self.bot.movepi(1.90, 1000)
    #     await self.bot.movepi(0.25, 2000)
    #     await self.bot.movepi(0.1, 2000)
    #     await self.bot.movepi(1.85, 3000)
    #     await self.bot.movepi(1.25, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 10, part 2 ###')
    #     await self.bot.movepi(0.35, 1000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 11 ###')
    #     await self.bot.use_teleporter(999/2400, 667/1080) # Aureate Elixir Furnace
    #     await self.bot.movepi(0.55, 2500)
    #     await self.bot.movepi(0.4, 2000)
    #     await self.bot.movepi(0.27, 1500)
    #     await self.bot.movepi(0.1, 500)
    #     await self.bot.movepi(0.45, 2500)
    #     await self.bot.movepi(0.3, 2000)
    #     await self.bot.movepi(0.00, 2500)
    #     await self.bot.movepi(1.90, 1000)
    #     await self.bot.movepi(0.25, 2000)
    #     await self.bot.movepi(0.1, 2000)
    #     await self.bot.movepi(1.85, 3000)
    #     await self.bot.movepi(1.75, 1800)
    #     await self.bot.movepi(1.27, 4000)
    #     await self.bot.movepi(1.51, 7000)
    #     await self.bot.movepi(1.05, 4000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()

    # async def farm_scalegorge_waterscape(self):
    #     await self.bot.switch_map(0.85, open_map=False, scroll_down=True)
    #     logger.info('### group 1 ###')
    #     await self.bot.use_teleporter(1641/2400, 530/1080, open_map=False)
    #     await self.bot.movepi(1.5, 4500)
    #     await self.bot.movepi(0.00, 2000)
    #     await self.bot.movepi(0.5, 3300)
    #     await self.bot.movepi(0.00, 3900)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2 ###')
    #     await self.bot.use_teleporter(357/2400, 612/1080)
    #     await self.bot.movepi(1.0, 5600)
    #     await self.bot.movepi(1.5, 1300)
    #     await self.bot.movepi(1.0, 6700)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2, part 2 ###') # roamer, can be improved
    #     await self.bot.movepi(1.0, 1500)
    #     await self.bot.movepi(0.75, 2500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 2, part 3 ###') # roamer, can be improved
    #     await self.bot.movepi(1.4, 1500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 3 ###') # move changed, not sure if teleport still works
    #     await self.bot.use_teleporter(693/2400, 695/1080) # Bud of Destruction
    #     await self.bot.movepi(1.5, 10800)
    #     await self.bot.movepi(0.00, 333)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 4 ###')
    #     await self.bot.use_teleporter(962/2400, 692/1080) # Bud of Destruction
    #     await self.bot.movepi(1.5, 7300)
    #     await self.bot.movepi(1.0, 9300)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 5 ###')
    #     await self.bot.use_teleporter(816/2400, 695/1080) # Bud of Destruction
    #     await self.bot.movepi(1.5, 1600)
    #     await self.bot.movepi(0.00, 3100)
    #     for _ in range(12):
    #         await self.bot.movepi(1.5, 650)
    #         await self.bot.movepi(0.00, 650)
    #     await self.bot.movepi(0.00, 6200)
    #     await self.bot.movepi(1.5, 2000)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 6 ###') # attack misses
    #     await self.bot.movepi(0.0, 1500)
    #     await self.bot.movepi(1.5, 500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 7 ###')
    #     await self.bot.use_teleporter(1196/2400, 361/1080) # Palace Ruin Depths
    #     await self.bot.movepi(1.5, 3000)
    #     await self.bot.movepi(0.00, 6500)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 8 ###')
    #     await self.bot.use_teleporter(926/2400, 618/1080) # Palace Ruin Depths
    #     await self.bot.movepi(1.5, 3000)
    #     await self.bot.movepi(0.00, 3600)
    #     await self.bot.movepi(1.5, 7100)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 9 ###')
    #     await self.bot.use_teleporter(848/2400, 257/1080) # Stagnant Shadow
    #     await self.bot.movepi(1.0, 3000)
    #     await self.bot.movepi(0.5, 750)
    #     await self.bot.movepi(1.0, 6700)
    #     await self.bot.attack()
    #     await self.bot.sleep(1)
    #     await self.bot.wait_for_onmap()
    #     logger.info('### group 10 ###')
    #     await self.bot.movepi(1.25, 250)
    #     await self.bot.attack()
    #     await self.bot.wait_for_onmap()
