version: 1
formatters:
  simple:
    format: '[%(asctime)-s] [%(levelname)-8s]  %(message)-s' # - is left align, s is size
    datefmt: '%y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: 'logs/app.log'
loggers:
  app:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console]